import placeholderEnemyUrl from "@assets/generated_images/enemy_bayou_wraith.png";
import { CLEARING_AIM_GEOMETRY } from "@shared/clearingCombatGeometry";

export const ELYSIAN_CLEARING_COMBAT_CONFIG = {
  enemyName: "Bayou Wraith",
  enemyImageUrl: placeholderEnemyUrl,
  naturalFacing: "right" as const,
  facingDeadZonePixels: 3,
  baseEnemyPopulation: 8,
  maxEnemyPopulation: 10,
  maxEnemies: 10,
  maxSimultaneousAttackers: 2,
  // Cluster anchors are consumed in encounter order, so interleave their
  // vertical positions instead of filling the top of the scene first.
  homes: [{ x: .28, y: .24 }, { x: .48, y: .58 }, { x: .43, y: .82 }, { x: .68, y: .28 }, { x: .25, y: .72 }, { x: .14, y: .52 }, { x: .35, y: .43 }, { x: .63, y: .72 }, { x: .86, y: .64 }, { x: .72, y: .48 }],
  initialSpawnDelayMs: [500, 1050, 1600, 2150, 2700, 3250, 3800, 4350, 4900, 5450],
  worldSize: { width: 1.7, height: 2.1 },
  worldBounds: { xMin: 0.08, xMax: 0.92, yMin: 0.05, yMax: 0.94 },
  roamRadiusPixels: 70,
  roamSpeedPixels: 34,
  pursuitSpeedPixels: 76,
  disengageRadiusPixels: 340,
  attackRangePixels: 82,
  attackWindupMs: 650,
  attackCooldownMs: 1450,
  playerEntryGraceMs: 1800,
  petInvulnerabilityMs: 700,
  respawnProtectionMs: 1600,
  respawnDelayMs: { min: 8000, max: 14000 },
  roamPauseMs: { min: 900, max: 2400 },
  meleeAttackRangePixels: CLEARING_AIM_GEOMETRY.meleeAttackRangePixels,
  meleeCapsuleRadiusPixels: CLEARING_AIM_GEOMETRY.meleeCapsuleRadiusPixels,
  meleeTargetAssistRadiusPixels: CLEARING_AIM_GEOMETRY.meleeTargetAssistRadiusPixels,
  meleePreferredConeDegrees: CLEARING_AIM_GEOMETRY.meleePreferredConeDegrees,
  meleeFallbackRadiusPixels: CLEARING_AIM_GEOMETRY.meleeFallbackRadiusPixels,
  lockedTargetAttackRangePixels: CLEARING_AIM_GEOMETRY.lockedTargetAttackRangePixels,
  weaponPointerSizePixels: 34,
  weaponPointerDistancePixels: 28,
  staffCapsuleRadiusPixels: CLEARING_AIM_GEOMETRY.staffCapsuleRadiusPixels,
  pickupRadiusPixels: 76,
  normalEnemyVisibleHeight: 38,
  bossEnemyVisibleHeight: 50,
  staffAttackRangePixels: 250,
  attackButtonSize: 62,
  petHealthBar: { width: 64, height: 6, gap: 7 },
  recentDamageDisplayMs: 1800,
  deathEffect: { size: 44, durationMs: 850, risePixels: 24 },
} as const;
