import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{buildClearingLoot,type ClearingLootItem}from"../server/clearingLoot";import{CLEARING_CHEST_REWARDS,isConfiguredClearingChestItem}from"../server/clearingRewardChests";
const items=Array.from({length:8},(_,i)=>({id:`i${i}`,name:`Item ${i}`,image_url:null,type:i%2?"food":"clearing",star_rarity:i>=6?3:i>=3?2:1,rarity:(i>=6?"rare":i>=3?"uncommon":"common")as"common"|"uncommon"|"rare",clearing_active:i%2===0,clearing_slot:i%2===0?"weapon":undefined}));
const rng=(values:number[])=>{let i=0;return()=>values[i++]??.4};
test("each confirmed regular defeat formula always constructs a complete chest bundle",()=>{const chest=buildClearingLoot(items,false,rng([0,.1,.2,.3,.4]));assert.ok(chest.items.length>=1);assert.ok(chest.coins>=1);assert.equal(chest.essence,0);assert.equal("exp" in chest,false)});
test("boss formula caps gear and keeps all rewards in one bundle",()=>{const chest=buildClearingLoot(items,true,rng([.99,.1,.5,.2,.4,.6,.2,.3]));assert.ok(chest.items.filter(i=>i.type==="clearing").length<=2);assert.ok(chest.coins>=3&&chest.coins<=5);assert.ok(chest.essence>=10&&chest.essence<=20)});
test("configured selection never duplicates an item",()=>{for(const boss of[false,true]){const chest=buildClearingLoot(items,boss,()=>.99);assert.equal(new Set(chest.items.map(i=>i.id)).size,chest.items.length)}});
test("admin-configured non-equipment items are eligible for Clearing chest rewards",()=>{const configured:ClearingLootItem={id:"potion",name:"Bayou Potion",image_url:"/potion.png",type:"consumable",star_rarity:0,rarity:"common"};assert.equal(isConfiguredClearingChestItem(configured),true);assert.deepEqual(buildClearingLoot([configured],false,rng([0,0,0,0])).items.map(item=>item.id),["potion"]);});
test("invalid Clearing equipment is excluded while an empty configured pool retains currency fallback",()=>{const inactive:ClearingLootItem={id:"retired",name:"Retired Sword",image_url:null,type:"clearing",star_rarity:1,rarity:"common",clearing_slot:"weapon",clearing_active:false};assert.equal(isConfiguredClearingChestItem(inactive),false);const fallback=buildClearingLoot([],false,rng([0,0]));assert.deepEqual(fallback.items,[]);assert.ok(fallback.coins>=1);});
test("chest generation reads the complete admin world pool instead of filtering it to gear",()=>{const source=readFileSync("server/clearingRewardChests.ts","utf8");assert.match(source,/WHERE d\.world_id=\$\{input\.worldId\}`/);assert.doesNotMatch(source,/WHERE d\.world_id=\$\{input\.worldId\} AND s\.type='clearing'/);});
test("unopened Clearing chests expire quickly instead of lingering between fights",()=>{assert.equal(CLEARING_CHEST_REWARDS.expirationMs,30_000);const layer=readFileSync("client/src/components/ClearingRewardChests.tsx","utf8");assert.match(layer,/expiry:\$\{chestId\}/);assert.match(layer,/chestDeadline\(chest\)-Date\.now\(\)/);});
test("Clearing chests claim on one tap and opened rewards dismiss automatically",()=>{const layer=readFileSync("client/src/components/ClearingRewardChests.tsx","utf8");assert.match(layer,/data-testid="clearing-chest-reward-arc"/);assert.match(layer,/inFlightChestIds=useRef<Set<string>>\(new Set\(\)\)/);assert.match(layer,/claimedChestIds=useRef<Set<string>>\(new Set\(\)\)/);assert.match(layer,/hiddenChestIds/);assert.match(layer,/fetch\(`\/api\/explore\/elysian-clearing\/chests\/\$\{chestId\}\/claim`/);assert.match(layer,/else void claimChest\(chest\)/);assert.match(layer,/OPENED_CHEST_DISPLAY_MS = 3200/);assert.match(layer,/schedule\(`dismiss:\$\{chestId\}`,[^\n]*OPENED_CHEST_DISPLAY_MS\)/);assert.match(layer,/queryClient\.invalidateQueries/);assert.match(layer,/Opening the chest is the claim/);assert.doesNotMatch(layer,/opened\?onCollect\(chest\):onOpen/);assert.doesNotMatch(layer,/role="dialog"|createPortal|ClearingChestModal/);});
test("Clearing reward arc keeps coins compact and makes other reward art more readable",()=>{const layer=readFileSync("client/src/components/ClearingRewardChests.tsx","utf8");assert.match(layer,/size==="coin"\?"h-7 w-7":"h-10 w-10"/);assert.match(layer,/name:"Coins"[^\n]*artSize:"coin"/);assert.match(layer,/name:"Essence"[^\n]*artSize:"reward"/);assert.match(layer,/artSize:"reward" as const/);});
test("Clearing chest art stays smaller than the active pet",()=>{const layer=readFileSync("client/src/components/ClearingRewardChests.tsx","utf8");assert.match(layer,/className="absolute h-11 w-11"/);assert.match(layer,/relative h-9 w-9 object-contain/);});

test("removed Clearing drops cannot be granted from stale chest snapshots",()=>{const source=readFileSync("server/clearingRewardChests.ts","utf8");assert.match(source,/sourceWorldId: input\.worldId/);assert.match(source,/SELECT 1 FROM clearing_world_drops WHERE world_id=\$\{rewards\.sourceWorldId\} AND shop_item_id=\$\{item\.shopItemId\} FOR SHARE/);assert.match(source,/Clearing duplicate chest claim blocked/);});
test("admin drop removal expires matching unclaimed reward snapshots atomically",()=>{const source=readFileSync("server/routes/clearingAdmin.routes.ts","utf8");assert.match(source,/db\.transaction/);assert.match(source,/SELECT world_id,shop_item_id FROM clearing_world_drops/);assert.match(source,/UPDATE clearing_reward_chests SET expires_at=LEAST\(expires_at,now\(\)\) WHERE claimed_at IS NULL/);assert.match(source,/sourceWorldId:row\.world_id/);assert.match(source,/shopItemId:row\.shop_item_id/);});
