import test from "node:test";import assert from "node:assert/strict";import{buildClearingLoot}from"../server/clearingLoot";import{effectiveClearingRarity}from"../shared/clearingConfig";
import { CLEARING_BALANCE } from "../shared/clearingConfig";
const pool=[
 {id:"c1",name:"C1",image_url:null,type:"gift",star_rarity:1,rarity:"common" as const},{id:"c2",name:"C2",image_url:null,type:"gift",star_rarity:1,rarity:"common" as const},{id:"u1",name:"U1",image_url:null,type:"food",star_rarity:2,rarity:"uncommon" as const},{id:"u2",name:"U2",image_url:null,type:"food",star_rarity:2,rarity:"uncommon" as const},{id:"r1",name:"R1",image_url:null,type:"clearing",star_rarity:3,rarity:"common" as const,clearing_active:true,clearing_slot:"weapon"},{id:"r2",name:"R2",image_url:null,type:"clearing",star_rarity:4,rarity:"rare" as const,clearing_active:true,clearing_slot:"armor"},
];
const sequence=(...values:number[])=>{let i=0;return()=>values[i++]??.5};
test("star override is shared and forces 3★–5★ Rare",()=>{for(const stars of[3,4,5])assert.equal(effectiveClearingRarity("common",stars),"rare");assert.equal(effectiveClearingRarity("uncommon",2),"uncommon")});
test("chest gear probabilities and caps are explicit balance values",()=>{assert.equal(CLEARING_BALANCE.regularChestGearChance,.30);assert.equal(CLEARING_BALANCE.bossChestGearChance,.65);assert.equal(CLEARING_BALANCE.regularChestMaxGearItems,1);assert.equal(CLEARING_BALANCE.bossChestMaxGearItems,2)});
test("regular chest has distinct configured items, 1–3 items, 1–2 coins, and no essence",()=>{const result=buildClearingLoot(pool,false,sequence(.99,.1,.1,.1,.1,.1));assert.ok(result.items.length>=1&&result.items.length<=3);assert.equal(new Set(result.items.map(i=>i.id)).size,result.items.length);assert.ok(result.coins>=1&&result.coins<=2);assert.equal(result.essence,0)});
test("boss chest has 3–5 distinct configured items and preserves both currencies",()=>{const result=buildClearingLoot(pool,true,sequence(.1,.1,.1,.1,.1,.1,.1,.1,.1));assert.ok(result.items.length>=3&&result.items.length<=5);assert.equal(new Set(result.items.map(i=>i.id)).size,result.items.length);assert.ok(result.coins>=3&&result.coins<=5);assert.ok(result.essence>=10&&result.essence<=20)});
test("a small pool caps safely without duplicate rewards",()=>{const result=buildClearingLoot(pool.slice(0,2),false,sequence(.99,.1,.1,.1,.1));assert.equal(result.items.length,2);assert.equal(new Set(result.items.map(i=>i.id)).size,2)});
test("an empty configured pool produces no unauthorized equipment",()=>{const result=buildClearingLoot([],true,sequence(.5,.5,.5));assert.deepEqual(result.items,[])});

test("gear rolls are separate from configured non-gear selection",()=>{const failed=buildClearingLoot(pool,false,sequence(0,.99,0,0,0,0));assert.equal(failed.items.some(i=>i.type==="clearing"),false);assert.ok(failed.items.some(i=>i.type!=="clearing"));const boss=buildClearingLoot(pool,true,sequence(.99,0,0,0,0,0,0,0,0,0));assert.ok(boss.items.some(i=>i.type==="clearing"));assert.ok(boss.items.filter(i=>i.type==="clearing").length<=2)});
