import assert from "node:assert/strict";
import test from "node:test";
import { CLEARING_BOSS_ENCOUNTER } from "../shared/clearingConfig";
import { ELYSIAN_CLEARING_FALLBACK_BOSS, advanceClearingBossEncounter, applyClearingHit, completeClearingBossEncounter, createClearingSession, recordClearingRegularDefeat } from "../server/elysianClearingCombat";

const templates=[{enemy_id:"regular",is_boss:false,name:"Mireling",image_url:null},{enemy_id:"boss",is_boss:true,name:"Bayou Ancient",image_url:null}];
const create=()=>createClearingSession("user","pet",{level:1,hp:1000,atk:50},1_000,()=>.25,templates);
const defeat=(session:ReturnType<typeof create>)=>{const enemy=session.enemies.find(candidate=>!candidate.defeated)!;enemy.health=1;const result=applyClearingHit({sessionId:session.id,instanceId:enemy.instanceId,userId:"user",petId:"pet",petDamage:50,enemyPosition:{x:enemy.x,y:enemy.y},maxRangePixels:10_000,attackActionId:`attack-${enemy.instanceId}`,now:1_100});assert.equal(result.status,"killed");return enemy;};

test("regular defeats count once and threshold prepares one server-owned boss",()=>{const session=create();for(let count=1;count<=CLEARING_BOSS_ENCOUNTER.regularDefeatThreshold;count++){const enemy=defeat(session);const progress=recordClearingRegularDefeat(session.id,enemy.instanceId,2_000+count);assert.equal(progress?.regularDefeats,count);recordClearingRegularDefeat(session.id,enemy.instanceId,3_000+count);assert.equal(session.clearingBossProgress.regularDefeats,count);}
assert.equal(session.clearingBossProgress.bossPhase,"preparing");assert.equal(advanceClearingBossEncounter({sessionId:session.id,userId:"attacker",now:99_000}),null,"another user cannot force a boss");assert.equal(advanceClearingBossEncounter({sessionId:session.id,userId:"user",now:session.clearingBossProgress.bossReadyAt!-1}),null,"client timing cannot force a boss");const boss=advanceClearingBossEncounter({sessionId:session.id,userId:"user",now:session.clearingBossProgress.bossReadyAt!});assert.equal(boss?.isBoss,true);assert.equal(session.enemies.length,1);assert.equal(advanceClearingBossEncounter({sessionId:session.id,userId:"user",now:99_000}),null,"boss spawns once");});

test("missing boss configuration falls back to the bundled Bayou Wraith",()=>{const session=createClearingSession("fallback-user","pet",{level:1,hp:1000,atk:50},1_000,()=>.25,[{enemy_id:"regular",is_boss:false,name:"Mireling",image_url:null}]);assert.equal(session.bossTemplate?.name,"Bayou Wraith");assert.equal(session.bossTemplate?.image_url,ELYSIAN_CLEARING_FALLBACK_BOSS.image_url);assert.ok(session.enemies.every(enemy=>!enemy.isBoss));session.clearingBossProgress={regularDefeats:CLEARING_BOSS_ENCOUNTER.regularDefeatThreshold,bossPhase:"preparing",bossReadyAt:2_000};const boss=advanceClearingBossEncounter({sessionId:session.id,userId:"fallback-user",now:2_000});assert.equal(boss?.name,"Bayou Wraith");assert.equal(boss?.imageUrl,"/world-assets/generated_images/enemy_bayou_wraith.png");});

test("an existing Bayou Wraith regular can be promoted without also spawning as a regular",()=>{const session=createClearingSession("wraith-user","pet",{level:1,hp:1000,atk:50},1_000,()=>.25,[{enemy_id:"wraith",is_boss:false,name:"Bayou Wraith",image_url:"/custom-wraith.png"},{enemy_id:"regular",is_boss:false,name:"Mireling",image_url:null}]);assert.equal(session.bossTemplate?.enemy_id,"wraith");assert.equal(session.bossTemplate?.is_boss,true);assert.ok(session.regularTemplates.every(template=>template.enemy_id!=="wraith"));assert.ok(session.enemies.every(enemy=>enemy.templateId!=="wraith"));});

test("boss completion is idempotent, resets progress, and resumes regular enemies",()=>{const session=create();session.clearingBossProgress={regularDefeats:CLEARING_BOSS_ENCOUNTER.regularDefeatThreshold,bossPhase:"preparing",bossReadyAt:2_000};const boss=advanceClearingBossEncounter({sessionId:session.id,userId:"user",now:2_000})!;boss.health=1;assert.equal(applyClearingHit({sessionId:session.id,instanceId:boss.instanceId,userId:"user",petId:"pet",petDamage:50,enemyPosition:{x:boss.x,y:boss.y},maxRangePixels:10_000,attackActionId:"boss-kill",now:2_100}).status,"killed");const regulars=completeClearingBossEncounter(session.id,boss.instanceId,2_200,()=>.25);assert.equal(regulars?.length,10);assert.ok(regulars?.every(enemy=>!enemy.isBoss));assert.deepEqual(session.clearingBossProgress,{regularDefeats:0,bossPhase:"regular",bossReadyAt:null});assert.equal(completeClearingBossEncounter(session.id,boss.instanceId,2_300),null,"boss completion cannot repeat");});
