import assert from "node:assert/strict";
import test from "node:test";
import { clusterHomes, engageConfirmedEnemy, enemyMinimumSeparation, enemyVisibleHeight, resetEnemyPassive, resolveEnemyPairs, type SimEnemy } from "../client/src/lib/clearingEnemyBehavior";
import { clearEnemyImageMetricsCache, enemyImageMetricsCacheSize, findAlphaBounds, loadEnemyImageMetrics, metricsFromBounds } from "../client/src/lib/enemyImageMetrics";
import { advanceClearingBossEncounter, applyClearingHit, createClearingSession, respawnClearingEnemy, selectClearingEncounterTemplates } from "../server/elysianClearingCombat";
import { clearingSpecialDamage, clearingSpecialHeal, resolveClearingAttackStyle, resolveClearingSpecialKind } from "../shared/clearingCombat";
import { CLEARING_EQUIPMENT_SALE_VALUES } from "../shared/clearingEquipment";

const enemy=(id:string,templateId="frog",boss=false):SimEnemy=>({instanceId:id,templateId,isBoss:boss,state:"roaming",engagedByPlayer:false,x:.5,y:.5,homeX:.5,homeY:.5,visibleHalfWidth:20});
test("walking near normal enemies and bosses does not engage either",()=>{const enemies=[enemy("a"),enemy("boss","boss",true)];assert.ok(enemies.every(e=>!e.engagedByPlayer&&e.state==="roaming"));});
test("only a confirmed hit engages its specific enemy; misses engage none",()=>{const enemies=[enemy("a"),enemy("b")];engageConfirmedEnemy(enemies,"a");assert.equal(enemies[0].engagedByPlayer,true);assert.equal(enemies[1].engagedByPlayer,false);engageConfirmedEnemy(enemies,"missing");assert.equal(enemies[1].engagedByPlayer,false);});
test("a returning enemy becomes passive at its group home",()=>{const e=enemy("a");e.engagedByPlayer=true;e.state="returning";resetEnemyPassive(e);assert.equal(e.engagedByPlayer,false);assert.equal(e.state,"roaming");});
test("server records confirmed engagement and respawns passive",()=>{const session=createClearingSession("polish-user","pet",{level:1,hp:1000,atk:50},1000),target=session.enemies[0];session.position={x:target.x,y:target.y,updatedAt:1000};assert.equal(target.engagedByPlayer,false);assert.equal(applyClearingHit({sessionId:session.id,instanceId:target.instanceId,userId:"polish-user",petId:"pet",now:2000}).status,"hit");assert.equal(target.engagedByPlayer,true);target.health=1;assert.equal(applyClearingHit({sessionId:session.id,instanceId:target.instanceId,userId:"polish-user",petId:"pet",now:2600}).status,"killed");const next=respawnClearingEnemy(session.id,target.instanceId);assert.equal(next?.engagedByPlayer,false);});
test("transparent padding does not change visible alpha footprint",()=>{const rgba=new Uint8ClampedArray(10*10*4);for(let y=3;y<7;y++)for(let x=2;x<6;x++)rgba[(y*10+x)*4+3]=255;const bounds=findAlphaBounds(rgba,10,10);assert.deepEqual(bounds,{left:2,top:3,right:5,bottom:6,width:4,height:4});assert.equal(metricsFromBounds(10,10,bounds).widthRatio,.4);});
test("image metric promises are cached once per URL",()=>{clearEnemyImageMetricsCache();const a=loadEnemyImageMetrics("synthetic://enemy"),b=loadEnemyImageMetrics("synthetic://enemy");assert.equal(a,b);assert.equal(enemyImageMetricsCacheSize(),1);void a.catch(()=>{});clearEnemyImageMetricsCache();});
test("same-template spacing is smaller and every pair resolves once",()=>{const a=enemy("a"),b=enemy("b"),c=enemy("c","bird");assert.ok(enemyMinimumSeparation(a,b)<enemyMinimumSeparation(a,c));assert.equal(resolveEnemyPairs([a,b,c],{width:400,height:800}),3);assert.ok(Math.hypot((a.x-b.x)*400,(a.y-b.y)*800)>0);});
test("same-kind packs share homes and split after three without stacking",()=>{const source=Array.from({length:6},(_,slot)=>({slot,templateId:"frog"})),homes=[{x:.4,y:.4},{x:.6,y:.6}],grouped=clusterHomes(source,homes);assert.equal(grouped[0].clusterId,"frog:0");assert.equal(grouped[2].clusterId,"frog:0");assert.equal(grouped[3].clusterId,"frog:1");assert.notDeepEqual(grouped[0],grouped[1]);});
test("encounters select regular enemies in packs of two or three",()=>{const templates=[{enemy_id:"frog",is_boss:false,name:"Frog",image_url:null},{enemy_id:"moth",is_boss:false,name:"Moth",image_url:null}],encounter=selectClearingEncounterTemplates(8,templates,()=>.4);assert.equal(encounter.length,8);for(let index=0;index<encounter.length;){const kind=encounter[index]?.enemy_id;let size=0;while(encounter[index+size]?.enemy_id===kind)size++;assert.ok(size>=2&&size<=3);index+=size;}});
test("boss threshold is server-owned, triggers once, rejects early combat, and resets after defeat",()=>{const templates=[{enemy_id:"frog",is_boss:false,name:"Frog",image_url:null},{enemy_id:"boss",is_boss:true,name:"Bog King",image_url:null}],session=createClearingSession("boss-user","pet",{level:1,hp:1000,atk:50},1000,()=>0,templates);assert.equal(session.enemies.some(enemy=>enemy.isBoss),false);for(let defeat=1;defeat<=10;defeat++){const target=session.enemies[0];target.defeated=true;target.health=0;const result=advanceClearingBossEncounter(session.id,target.instanceId,2000+defeat,()=>0)!;assert.equal(result.progress.regularDefeats,defeat);if(defeat<10)assert.equal(result.progress.phase,"regular");}const boss=session.enemies[0];assert.equal(boss.isBoss,true);assert.equal(session.bossPhase,"preparing");assert.equal(advanceClearingBossEncounter(session.id,"already-counted",3000),null);assert.equal(applyClearingHit({sessionId:session.id,instanceId:boss.instanceId,userId:"boss-user",petId:"pet",now:3000}).status,"target_locked");boss.defeated=true;boss.health=0;const reset=advanceClearingBossEncounter(session.id,boss.instanceId,4000,()=>0)!;assert.equal(reset.progress.regularDefeats,0);assert.equal(reset.progress.phase,"regular");assert.equal(reset.nextEnemy?.isBoss,false);});
test("enemy art uses the single configured smaller regular and boss sizes",()=>{assert.equal(enemyVisibleHeight(false),28);assert.equal(enemyVisibleHeight(true),38);});
test("attack style precedence and name fallbacks remain safe",()=>{assert.equal(resolveClearingAttackStyle({attackStyle:"staff_orb",name:"Sword"}),"staff_orb");assert.equal(resolveClearingAttackStyle({name:"MOON SWORD"}),"sword_slash");assert.equal(resolveClearingAttackStyle({name:"Reed Staff"}),"staff_orb");assert.equal(resolveClearingAttackStyle({name:"Claw"}),"default_melee");});
test("Clearing specials route configured and legacy heals without weakening attacks",()=>{assert.equal(resolveClearingSpecialKind({skillType:"heal"}),"heal");assert.equal(resolveClearingSpecialKind({specialSkill:"Heal Party"}),"heal");assert.equal(resolveClearingSpecialKind({specialSkillType:"Lazer"}),"damage");assert.equal(resolveClearingSpecialKind({}),null);assert.equal(clearingSpecialDamage(100),175);assert.equal(clearingSpecialHeal(1000),300);});
test("staff range is longer but remains server validated",()=>{const session=createClearingSession("range-user","pet",{level:1,hp:1000,atk:50},1000),target=session.enemies[0];session.position={x:target.x-.5,y:target.y,updatedAt:1000};assert.equal(applyClearingHit({sessionId:session.id,instanceId:target.instanceId,userId:"range-user",petId:"pet",enemyPosition:{x:target.x,y:target.y},maxRangePixels:145,now:2000}).status,"range");assert.equal(applyClearingHit({sessionId:session.id,instanceId:target.instanceId,userId:"range-user",petId:"pet",enemyPosition:{x:target.x,y:target.y},maxRangePixels:270,now:2000}).status,"hit");});
test("Clearing sale values from PR 66 remain unchanged",()=>assert.deepEqual(CLEARING_EQUIPMENT_SALE_VALUES,{1:25,2:50,3:100,4:300,5:500}));

test("validated enemy position becomes the exact final death coordinate",()=>{const session=createClearingSession("drop-position-user","pet",{level:1,hp:1000,atk:5000},1000),target=session.enemies[0],finalPosition={x:target.x+.02,y:target.y+.015};session.position={...finalPosition,updatedAt:1000};target.health=1;const result=applyClearingHit({sessionId:session.id,instanceId:target.instanceId,userId:"drop-position-user",petId:"pet",enemyPosition:finalPosition,now:2000});assert.equal(result.status,"killed");assert.deepEqual({x:target.x,y:target.y},finalPosition);});
