import {sql} from "drizzle-orm";
import {DEFAULT_CLEARING_SHOP,clearingShopPurchaseRadius,isWithinClearingShopRadius,normalizeClearingPortalWidth} from "@shared/clearingShop";
import {getClearingSession} from "./elysianClearingCombat";
export class ClearingShopError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
const mapConfig=(row:any,items:any[]=[])=>({id:row.id,worldId:row.world_id,enabled:row.enabled,portalX:Number(row.portal_x),portalY:Number(row.portal_y),portalWidth:normalizeClearingPortalWidth(row.portal_width),interactionRadiusPixels:Number(row.interaction_radius_pixels),items:items.map(i=>({assignmentId:i.assignment_id,shopItemId:i.shop_item_id,name:i.name,imageUrl:i.image_url,type:i.type,essencePrice:Number(i.essence_price),active:i.active,sortOrder:Number(i.sort_order),starRarity:i.star_rarity,healthRestored:i.health_restored,manaRestored:i.mana_restored,atkBoost:i.atk_boost,defBoost:i.def_boost,healthBoost:i.health_boost}))});
export async function getClearingShop(db:any,worldId:string,includeInactive=false){const c=await db.execute(sql`SELECT * FROM clearing_world_shops WHERE world_id=${worldId}`);const row=(c.rows[0] as any)??{id:"",world_id:worldId,enabled:DEFAULT_CLEARING_SHOP.enabled,portal_x:DEFAULT_CLEARING_SHOP.portalX,portal_y:DEFAULT_CLEARING_SHOP.portalY,portal_width:DEFAULT_CLEARING_SHOP.portalWidth,interaction_radius_pixels:DEFAULT_CLEARING_SHOP.interactionRadiusPixels};const items=await db.execute(sql`SELECT a.id assignment_id,a.shop_item_id,a.essence_price,a.active,a.sort_order,s.name,s.image_url,s.type,s.star_rarity,s.health_restored,s.mana_restored,s.atk_boost,s.def_boost,s.health_boost FROM clearing_world_shop_items a JOIN shop_items s ON s.id=a.shop_item_id WHERE a.world_id=${worldId} ${includeInactive?sql``:sql`AND a.active=true`} ORDER BY a.sort_order,a.created_at`);return mapConfig(row,items.rows as any[])}
async function grant(tx:any,userId:string,item:any){if(item.type==='potion'||item.type==='edibles'){const cap=item.type==='potion'?50:30;await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${userId})::int,hashtext(${item.shop_item_id})::int)`);const found=await tx.execute(sql`SELECT id,quantity FROM user_inventory WHERE user_id=${userId} AND shop_item_id=${item.shop_item_id} AND COALESCE(quantity,1)<${cap} ORDER BY acquired_at FOR UPDATE LIMIT 1`);if(found.rows.length){const id=(found.rows[0] as any).id;return (await tx.execute(sql`UPDATE user_inventory SET quantity=LEAST(${cap},COALESCE(quantity,1)+1) WHERE id=${id} RETURNING *`)).rows[0];}}
 return (await tx.execute(sql`INSERT INTO user_inventory(user_id,shop_item_id,quantity,is_hatched) VALUES(${userId},${item.shop_item_id},1,${false}) RETURNING *`)).rows[0];}
export async function purchaseClearingShopItem(db:any,input:{userId:string;sessionId:string;assignmentId:string;purchaseActionId:string;quantity:1}){const session=getClearingSession(input.sessionId);if(!session||session.userId!==input.userId)throw new ClearingShopError(403,"INVALID_SESSION","Clearing session does not belong to this player");return db.transaction(async(tx:any)=>{const prior=await tx.execute(sql`SELECT * FROM clearing_shop_purchases WHERE purchase_action_id=${input.purchaseActionId}::uuid`);if(prior.rows.length){const p=prior.rows[0] as any;return{idempotent:true,essence:Number(p.resulting_essence),inventoryItem:{id:p.inventory_id}}}
 const found=await tx.execute(sql`SELECT a.*,c.enabled,c.portal_x,c.portal_y,c.interaction_radius_pixels,s.name,s.type FROM clearing_world_shop_items a JOIN clearing_world_shops c ON c.world_id=a.world_id JOIN shop_items s ON s.id=a.shop_item_id WHERE a.id=${input.assignmentId} FOR UPDATE OF a`);const item=found.rows[0] as any;if(!item||!item.active||!item.enabled)throw new ClearingShopError(409,"ITEM_UNAVAILABLE","Shop item is unavailable");const price=Number(item.essence_price);if(!Number.isSafeInteger(price)||price<1)throw new ClearingShopError(409,"INVALID_PRICE","Shop price is invalid");const world=session.worldPixels??{width:1000,height:1000};const purchaseRadius=clearingShopPurchaseRadius(Number(item.interaction_radius_pixels));if(!isWithinClearingShopRadius(session.position,{x:Number(item.portal_x),y:Number(item.portal_y)},world,purchaseRadius))throw new ClearingShopError(409,"TOO_FAR","Move closer to the shop portal");const debit=await tx.execute(sql`UPDATE users SET essence=essence-${price} WHERE id=${input.userId} AND essence>=${price} RETURNING essence`);if(!debit.rows.length)throw new ClearingShopError(409,"INSUFFICIENT_ESSENCE","Not enough Essence");const inventory=await grant(tx,input.userId,item),essence=Number((debit.rows[0] as any).essence);await tx.execute(sql`INSERT INTO clearing_shop_purchases(purchase_action_id,user_id,assignment_id,inventory_id,essence_spent,resulting_essence) VALUES(${input.purchaseActionId}::uuid,${input.userId},${input.assignmentId},${inventory.id},${price},${essence})`);return{idempotent:false,essence,inventoryItem:inventory,granted:{name:item.name,shopItemId:item.shop_item_id}};});}
