export type ClearingPoint = { x: number; y: number };
export type ClearingDirection = { dx: number; dy: number };
export const CLEARING_AIM_GEOMETRY = { worldWidthPixels:400,worldHeightPixels:800,meleeAttackRangePixels:155,meleeCapsuleRadiusPixels:24,meleeTargetAssistRadiusPixels:205,meleePreferredConeDegrees:120,meleeFallbackRadiusPixels:185,meleeLockHysteresisPixels:18,meleeDisengageRangePixels:223,staffAttackRangePixels:250,staffCapsuleRadiusPixels:22,playerMovementSpeedPixelsPerSecond:90,positionJitterAllowancePixels:55,serverAimPointTolerancePixels:18,serverEnemyPositionTolerancePixels:240 } as const;
export function normalizeClearingDirection(value:unknown):ClearingDirection|null{if(!value||typeof value!=="object")return null;const{dx,dy}=value as ClearingDirection;if(!Number.isFinite(dx)||!Number.isFinite(dy))return null;const length=Math.hypot(dx,dy);return length<.001?null:{dx:dx/length,dy:dy/length};}
export function isFiniteClearingPoint(value:unknown):value is ClearingPoint{return Boolean(value&&typeof value==="object"&&Number.isFinite((value as ClearingPoint).x)&&Number.isFinite((value as ClearingPoint).y));}
export function clearingPointInDirection(origin:ClearingPoint,direction:ClearingDirection,pixels:number,world:{width:number;height:number}):ClearingPoint|null{const n=normalizeClearingDirection(direction);if(!isFiniteClearingPoint(origin)||!n||!Number.isFinite(pixels)||!Number.isFinite(world.width)||!Number.isFinite(world.height)||world.width<=0||world.height<=0)return null;return{x:origin.x+n.dx*pixels/world.width,y:origin.y+n.dy*pixels/world.height};}
export function clearingPixelDelta(from:ClearingPoint,to:ClearingPoint,world:{width:number;height:number}){if(!isFiniteClearingPoint(from)||!isFiniteClearingPoint(to)||!Number.isFinite(world.width)||!Number.isFinite(world.height))return null;return{dx:(to.x-from.x)*world.width,dy:(to.y-from.y)*world.height};}
export function clearingHitboxEdgeDistance(from:ClearingPoint,to:ClearingPoint,radiusPixels:number,world:{width:number;height:number}){const delta=clearingPixelDelta(from,to,world);return delta?Math.max(0,Math.hypot(delta.dx,delta.dy)-Math.max(0,Number(radiusPixels)||0)):Infinity;}
export function clearingDistanceToRay(origin:ClearingPoint,direction:ClearingDirection,point:ClearingPoint,maxLength:number,world:{width:number;height:number}){const n=normalizeClearingDirection(direction),d=clearingPixelDelta(origin,point,world);if(!n||!d||!Number.isFinite(maxLength)||maxLength<0)return null;const along=d.dx*n.dx+d.dy*n.dy,clamped=Math.max(0,Math.min(maxLength,along));return{along,distance:Math.hypot(d.dx-n.dx*clamped,d.dy-n.dy*clamped)};}
