import { worldYToDepth } from "@/lib/clearingWorldPresentation";

export const CLEARING_PORTAL_PARTICLES=[
  {x:12,y:13,delay:0,size:4,rise:48,star:false,color:"#86efac"},{x:21,y:5,delay:.8,size:3,rise:56,star:false,color:"#bef264"},
  {x:30,y:18,delay:1.45,size:5,rise:50,star:true,color:"#d9f99d"},{x:39,y:9,delay:.35,size:3,rise:61,star:false,color:"#4ade80"},
  {x:48,y:2,delay:1.1,size:4,rise:53,star:false,color:"#a3e635"},{x:57,y:16,delay:.15,size:3,rise:58,star:false,color:"#bbf7d0"},
  {x:67,y:7,delay:1.65,size:6,rise:49,star:true,color:"#ecfccb"},{x:78,y:14,delay:.65,size:3,rise:59,star:false,color:"#34d399"},
  {x:88,y:4,delay:1.9,size:4,rise:54,star:false,color:"#d9f99d"},{x:17,y:24,delay:2.1,size:3,rise:46,star:false,color:"#bef264"},
  {x:27,y:31,delay:.25,size:4,rise:62,star:false,color:"#4ade80"},{x:43,y:27,delay:1.3,size:5,rise:51,star:true,color:"#fef08a"},
  {x:54,y:35,delay:.55,size:3,rise:57,star:false,color:"#86efac"},{x:64,y:25,delay:1.75,size:3,rise:64,star:false,color:"#a3e635"},
  {x:74,y:33,delay:.95,size:4,rise:52,star:false,color:"#bbf7d0"},{x:84,y:27,delay:2.25,size:5,rise:60,star:true,color:"#d9f99d"},
] as const;

export default function ClearingShopPortal({x,y,width,editing=false,disabledPreview=false,onPointerDown}:{x:number;y:number;width:number;editing?:boolean;disabledPreview?:boolean;onPointerDown?:(event:React.PointerEvent<HTMLDivElement>)=>void}){
  return <div data-testid="clearing-shop-portal" data-interactive={editing||undefined} onPointerDown={editing?onPointerDown:undefined} className={`clearing-shop-portal absolute overflow-visible ${editing?"is-editing pointer-events-auto":"pointer-events-none"}`} style={{left:`${x*100}%`,top:`${y*100}%`,width,height:104,transform:"translate(-50%,-91px)",zIndex:worldYToDepth(y,0),touchAction:"none"}}>
    <span className="portal-glow" aria-hidden/>
    <span className="portal-motes" aria-hidden>{CLEARING_PORTAL_PARTICLES.map((particle,index)=><b key={index} data-star={particle.star||undefined} style={{left:`${particle.x}%`,bottom:`${particle.y}%`,width:particle.size,height:particle.size,animationDelay:`-${particle.delay}s`,background:particle.color,color:particle.color,"--portal-rise":`${particle.rise}px`} as React.CSSProperties}/>)}</span>
    {editing&&<><span className="portal-editor-outline" aria-hidden/><span className="portal-center-marker" aria-hidden/><span className="portal-editor-label">Admin-only placement guide</span></>}
    {disabledPreview&&<span className="portal-disabled-badge">Disabled preview</span>}
    <style>{`.clearing-shop-portal{isolation:isolate}.portal-glow{position:absolute;inset:8% 17% 4%;border-radius:48% 48% 40% 40%;background:radial-gradient(ellipse at 50% 72%,rgba(163,230,53,.13),rgba(74,222,128,.055) 48%,transparent 76%);filter:blur(5px);pointer-events:none}.portal-motes{position:absolute;inset:0;pointer-events:none}.portal-motes b{position:absolute;border-radius:50%;box-shadow:0 0 5px currentColor,0 0 9px rgba(190,242,100,.35);animation:clearing-portal-rise 3.4s ease-in-out infinite;pointer-events:none}.portal-motes b[data-star]{border-radius:0;clip-path:polygon(50% 0,61% 38%,100% 50%,61% 62%,50% 100%,39% 62%,0 50%,39% 38%);animation-name:clearing-portal-twinkle}.portal-editor-outline{position:absolute;inset:2px 5%;border:1px dashed rgba(253,230,138,.95);border-radius:42% 42% 34% 34%;cursor:grab;background:rgba(163,230,53,.025)}.is-editing:active .portal-editor-outline{cursor:grabbing}.portal-center-marker{position:absolute;left:50%;bottom:10%;width:12px;height:12px;transform:translate(-50%,50%);border:1px solid #fde68a;border-radius:50%;box-shadow:0 0 0 2px rgba(0,0,0,.35)}.portal-center-marker:before,.portal-center-marker:after{content:"";position:absolute;background:#fde68a}.portal-center-marker:before{left:5px;top:-4px;width:1px;height:18px}.portal-center-marker:after{left:-4px;top:5px;width:18px;height:1px}.portal-editor-label,.portal-disabled-badge{position:absolute;left:50%;transform:translateX(-50%);white-space:nowrap;border:1px solid rgba(253,230,138,.7);border-radius:999px;background:rgba(35,25,14,.94);padding:2px 7px;font-size:9px;font-weight:800;color:#fef3c7}.portal-editor-label{top:-17px}.portal-disabled-badge{bottom:-17px}@keyframes clearing-portal-rise{0%{opacity:0;transform:translateY(5px) scale(.55)}28%{opacity:.9}75%{opacity:.55}100%{opacity:0;transform:translateY(calc(-1 * var(--portal-rise))) scale(1.05)}}@keyframes clearing-portal-twinkle{0%,20%,100%{opacity:.12;transform:translateY(0) scale(.45) rotate(0)}45%{opacity:1;transform:translateY(calc(-.45 * var(--portal-rise))) scale(1.2) rotate(18deg)}75%{opacity:.25;transform:translateY(calc(-1 * var(--portal-rise))) scale(.65) rotate(36deg)}}@media(prefers-reduced-motion:reduce){.portal-motes b{animation:none;opacity:.65;transform:translateY(-18px)}.portal-motes b[data-star]{opacity:.75}}`}</style>
  </div>;
}
