import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2 } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { CLEARING_SHOP_LIMITS, DEFAULT_CLEARING_SHOP, type ClearingShopConfig, type ClearingShopItem } from "@shared/clearingShop";
import { ClearingAddItemModal, ClearingAssignmentCard } from "./ClearingAdminSections";

const card="rounded-2xl border border-amber-700/35 bg-gradient-to-b from-[#332516]/90 to-[#17120c]/90 p-4 shadow-lg";
const button="min-h-11 rounded-xl border border-amber-500/60 bg-amber-700 px-4 py-2 text-sm font-black text-amber-50 disabled:opacity-50";
const field="min-h-11 w-full rounded-xl border border-amber-700/40 bg-black/35 px-3 text-amber-50";
type PortalDraft={portalWidth:string;interactionRadiusPixels:string};
type ItemDraft={essencePrice:string;sortOrder:string;active:boolean};

export default function ClearingShopAdmin({worldId,catalog}:{worldId:string;catalog:any[]}){
  const qc=useQueryClient(),{toast}=useToast(),key=["/api/admin/clearing/worlds",worldId,"shop"];
  const shop=useQuery<ClearingShopConfig>({queryKey:key});
  const [portal,setPortal]=useState<PortalDraft>({portalWidth:"",interactionRadiusPixels:""});
  const [itemDrafts,setItemDrafts]=useState<Record<string,ItemDraft>>({});
  const [addOpen,setAddOpen]=useState(false),[addPrices,setAddPrices]=useState<Record<string,string>>({});
  useEffect(()=>{if(shop.data)setPortal({portalWidth:String(shop.data.portalWidth),interactionRadiusPixels:String(shop.data.interactionRadiusPixels)})},[shop.data?.portalWidth,shop.data?.interactionRadiusPixels]);
  useEffect(()=>{if(shop.data)setItemDrafts(Object.fromEntries(shop.data.items.map(item=>[item.assignmentId,{essencePrice:String(item.essencePrice),sortOrder:String(item.sortOrder),active:item.active}])));},[shop.data?.items]);
  const save=useMutation({mutationFn:({method,url,body}:{method:string;url:string;body?:unknown})=>apiRequest(method,url,body),onSuccess:()=>{void qc.invalidateQueries({queryKey:key});toast({title:"Saved",description:"Clearing shop changes are now live."})},onError:(error:Error)=>toast({title:"Shop update failed",description:error.message||"Please try again.",variant:"destructive"})});
  const patch=(body:unknown)=>save.mutate({method:"PATCH",url:`/api/admin/clearing/worlds/${worldId}/shop`,body});
  const available=useMemo(()=>{const assigned=new Set(shop.data?.items.map(item=>item.shopItemId));return catalog.filter(item=>!assigned.has(item.id))},[catalog,shop.data?.items]);
  if(shop.isLoading||!shop.data)return <div className="h-64 animate-pulse rounded-2xl bg-amber-950/30" aria-label="Loading Clearing shop"/>;
  const width=Number(portal.portalWidth),radius=Number(portal.interactionRadiusPixels);
  const portalValid=Number.isInteger(width)&&width>=CLEARING_SHOP_LIMITS.widthMin&&width<=CLEARING_SHOP_LIMITS.widthMax&&Number.isInteger(radius)&&radius>=CLEARING_SHOP_LIMITS.radiusMin&&radius<=CLEARING_SHOP_LIMITS.radiusMax;
  const portalDirty=width!==shop.data.portalWidth||radius!==shop.data.interactionRadiusPixels;
  const resetPortal=()=>setPortal({portalWidth:String(DEFAULT_CLEARING_SHOP.portalWidth),interactionRadiusPixels:String(DEFAULT_CLEARING_SHOP.interactionRadiusPixels)});
  return <div className="space-y-4">
    <section className={card}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="text-lg font-black text-amber-100">Portal Status</h3><p className="mt-1 text-sm text-stone-300">Players enter the glowing tree opening to access the Essence shop.</p></div><label className="flex min-h-11 items-center gap-3 rounded-xl border border-amber-700/40 bg-black/25 px-3 font-bold"><input aria-label="Enable Clearing shop portal" type="checkbox" checked={shop.data.enabled} disabled={save.isPending} onChange={event=>patch({enabled:event.target.checked})}/><span>{shop.data.enabled?"Enabled for players":"Disabled for players"}</span></label></div><button type="button" className={`${button} mt-3`} onClick={()=>toast({title:"Open the Clearing",description:"Use the admin-only Edit Portal button in the Clearing to drag the placement guide."})}>Edit Portal Placement</button></section>
    <section className={card}><h3 className="text-lg font-black text-amber-100">Portal Interaction Settings</h3><p className="mt-1 text-xs text-stone-400">Values remain local until Save Changes is pressed.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-amber-200">Portal visual width<input aria-label="Portal visual width" className={`${field} mt-1`} type="number" min={CLEARING_SHOP_LIMITS.widthMin} max={CLEARING_SHOP_LIMITS.widthMax} value={portal.portalWidth} onChange={event=>setPortal(value=>({...value,portalWidth:event.target.value}))}/></label><label className="text-sm font-bold text-amber-200">Interaction radius (pixels)<input aria-label="Portal interaction radius" className={`${field} mt-1`} type="number" min={CLEARING_SHOP_LIMITS.radiusMin} max={CLEARING_SHOP_LIMITS.radiusMax} value={portal.interactionRadiusPixels} onChange={event=>setPortal(value=>({...value,interactionRadiusPixels:event.target.value}))}/></label></div><div className="mt-3 rounded-xl bg-black/25 p-3 text-xs text-stone-300">Current stored position: <strong>X {shop.data.portalX.toFixed(3)} · Y {shop.data.portalY.toFixed(3)}</strong></div>{!portalValid&&<p role="alert" className="mt-2 text-xs font-bold text-red-300">Width must be {CLEARING_SHOP_LIMITS.widthMin}–{CLEARING_SHOP_LIMITS.widthMax}; radius must be {CLEARING_SHOP_LIMITS.radiusMin}–{CLEARING_SHOP_LIMITS.radiusMax} whole pixels.</p>}<div className="mt-3 flex flex-wrap gap-2"><button className={button} type="button" onClick={resetPortal}>Reset to default</button><button className={button} type="button" disabled={!portalDirty||save.isPending} onClick={()=>setPortal({portalWidth:String(shop.data!.portalWidth),interactionRadiusPixels:String(shop.data!.interactionRadiusPixels)})}>Cancel</button><button className={button} type="button" disabled={!portalDirty||!portalValid||save.isPending} onClick={()=>patch({portalWidth:width,interactionRadiusPixels:radius})}>{save.isPending?"Saving…":"Save Changes"}</button></div></section>
    <section className={card}><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-black text-amber-100">Assigned Essence Shop Items</h3><p className="text-xs text-stone-400">{shop.data.items.length} configured</p></div><button className={button} onClick={()=>setAddOpen(true)}><Plus className="mr-1 inline h-4 w-4"/>Add Shop Item</button></div><div className="mt-3 space-y-2">{shop.data.items.map(item=>{const draft=itemDrafts[item.assignmentId]??itemToDraft(item),dirty=draft.essencePrice!==String(item.essencePrice)||draft.sortOrder!==String(item.sortOrder)||draft.active!==item.active,valid=positiveInt(draft.essencePrice)&&integer(draft.sortOrder);return <ClearingAssignmentCard key={item.assignmentId} image={item.imageUrl} name={item.name} details={`${item.type}${item.starRarity?` · ${item.starRarity}★`:""}`} actions={<div className="grid w-full gap-2 sm:w-auto sm:grid-cols-[7rem_6rem_auto] sm:items-end"><label className="text-xs font-bold">Essence price<input className={`${field} mt-1`} aria-label={`${item.name} Essence price`} type="number" min="1" value={draft.essencePrice} onChange={event=>updateItem(setItemDrafts,item.assignmentId,{essencePrice:event.target.value})}/></label><label className="text-xs font-bold">Sort order<input className={`${field} mt-1`} aria-label={`${item.name} sort order`} type="number" value={draft.sortOrder} onChange={event=>updateItem(setItemDrafts,item.assignmentId,{sortOrder:event.target.value})}/></label><label className="flex min-h-11 items-center gap-2 text-xs font-bold"><input type="checkbox" aria-label={`${item.name} active`} checked={draft.active} onChange={event=>updateItem(setItemDrafts,item.assignmentId,{active:event.target.checked})}/>Active</label><button className={button} disabled={!dirty||!valid||save.isPending} onClick={()=>save.mutate({method:"PATCH",url:`/api/admin/clearing/shop/items/${item.assignmentId}`,body:{essencePrice:Number(draft.essencePrice),sortOrder:Number(draft.sortOrder),active:draft.active}})}>Save</button><button aria-label={`Remove ${item.name}`} className={`${button} border-red-500/50 bg-red-950`} disabled={save.isPending} onClick={()=>{if(window.confirm(`Remove ${item.name} from the Essence shop?`))save.mutate({method:"DELETE",url:`/api/admin/clearing/shop/items/${item.assignmentId}`})}}><Trash2 className="mx-auto h-4 w-4"/></button></div>}/>})}{!shop.data.items.length&&<p className="rounded-xl border border-dashed border-amber-700/40 p-7 text-center text-sm text-stone-400">No Essence shop items are assigned.</p>}</div></section>
    {addOpen&&<ClearingAddItemModal title="Add Shop Item" searchLabel="Search catalog by name" items={available} onClose={()=>setAddOpen(false)} render={item=>{const price=addPrices[item.id]??"";return <div key={item.id} className="flex flex-col gap-3 rounded-xl border border-amber-800/35 bg-black/25 p-3 sm:flex-row sm:items-center"><img src={item.imageUrl||""} alt="" className="h-14 w-14 object-contain"/><div className="min-w-0 flex-1"><strong>{item.name}</strong><p className="text-xs text-stone-400">{item.price??0} coins normally · coin price remains unchanged</p></div><label className="text-xs font-bold">Essence price<input className={`${field} mt-1 sm:w-28`} aria-label={`${item.name} new Essence price`} type="number" min="1" value={price} onChange={event=>setAddPrices(values=>({...values,[item.id]:event.target.value}))}/></label><button className={button} disabled={!positiveInt(price)||save.isPending} onClick={()=>save.mutate({method:"POST",url:`/api/admin/clearing/worlds/${worldId}/shop/items`,body:{shopItemId:item.id,essencePrice:Number(price)}})}>Add</button></div>}}/>}
  </div>;
}
const itemToDraft=(item:ClearingShopItem):ItemDraft=>({essencePrice:String(item.essencePrice),sortOrder:String(item.sortOrder),active:item.active});
const updateItem=(set:React.Dispatch<React.SetStateAction<Record<string,ItemDraft>>>,id:string,patch:Partial<ItemDraft>)=>set(values=>({...values,[id]:{...values[id],...patch}}));
const positiveInt=(value:string)=>Number.isInteger(Number(value))&&Number(value)>0&&Number(value)<=CLEARING_SHOP_LIMITS.maxPrice;
const integer=(value:string)=>Number.isInteger(Number(value))&&Number(value)>=-10000&&Number(value)<=10000;
