import { useState } from "react";
import { activeClearingShopItems, type ClearingShopConfig, type ClearingShopItem } from "@shared/clearingShop";
import { currencyAssets } from "@/lib/currencyAssets";

export default function ClearingShopOverlay({shop,essence,busy,onBuy,onClose}:{shop:ClearingShopConfig;essence:number;busy:boolean;onBuy:(id:string)=>Promise<any>;onClose:()=>void}){
  const [pending,setPending]=useState<ClearingShopItem|null>(null),[message,setMessage]=useState("");
  const activeItems=activeClearingShopItems(shop.items);
  const confirm=async()=>{if(!pending)return;try{const result=await onBuy(pending.assignmentId);setMessage(`${result.granted?.name||pending.name} added to inventory`);setPending(null)}catch(error){setMessage(error instanceof Error?error.message:"Purchase failed")}};
  return <div data-interactive role="dialog" aria-modal="true" aria-labelledby="clearing-shop-title" className="fixed inset-0 pointer-events-auto flex items-center justify-center bg-black/70 p-3" style={{zIndex:6000,paddingTop:"max(12px,env(safe-area-inset-top))",paddingBottom:"max(12px,env(safe-area-inset-bottom))"}}>
    <section className="flex max-h-full min-h-[22rem] w-full max-w-md flex-col overflow-hidden rounded-2xl border border-amber-400/70 text-amber-50 shadow-2xl" style={{background:"radial-gradient(circle at 50% 0,#185b3a 0,#082c20 42%,#031a13 100%)",boxShadow:"0 0 24px #10b98155"}}>
      <header className="flex items-center gap-3 border-b border-amber-500/40 p-4"><h2 id="clearing-shop-title" className="flex-1 text-xl font-black">Clearing Shop</h2><span data-testid="clearing-shop-essence" className="flex items-center gap-1 font-bold"><img src={currencyAssets.essenceToken} alt="Essence" className="h-6 w-6 object-contain"/>{essence}</span><button type="button" className="rounded-full border border-amber-200/50 px-3 py-1" onClick={onClose} aria-label="Close shop">✕</button></header>
      {message&&<p className="border-b border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-sm text-emerald-100">✦ {message}</p>}
      {activeItems.length===0?<div data-testid="clearing-shop-empty-state" className="relative flex flex-1 flex-col items-center justify-center overflow-hidden px-8 py-12 text-center"><span aria-hidden className="absolute h-28 w-28 rounded-full border border-amber-300/20 bg-emerald-300/5 shadow-[0_0_35px_rgba(52,211,153,.2)]"/><div aria-hidden className="relative mb-5 flex h-16 w-16 items-center justify-center rounded-full border border-amber-300/35 bg-emerald-900/70 text-2xl text-emerald-200 shadow-[0_0_22px_rgba(52,211,153,.45)]"><i className="absolute -left-5 top-1 text-xs text-emerald-300">✦</i><i className="absolute -right-4 bottom-2 text-[10px] text-amber-200">✧</i>●</div><h3 className="relative text-lg font-black text-amber-100">No Wares Available Yet</h3><p className="relative mt-3 whitespace-pre-line text-sm leading-6 text-emerald-100">{"The shopkeeper is still gathering their wares.\nCheck back again soon!"}</p></div>:<div data-testid="clearing-shop-item-grid" className="grid flex-1 grid-cols-2 gap-3 overflow-y-auto p-3">{activeItems.map(item=><article key={item.assignmentId} className="flex flex-col rounded-xl border border-amber-500/30 bg-black/25 p-3"><img src={item.imageUrl||""} alt="" className="mx-auto h-20 w-20 object-contain"/><h3 className="mt-2 font-bold">{item.name}</h3><small className="min-h-8 text-emerald-100/75">{item.healthRestored?`Restores ${item.healthRestored} health`:item.atkBoost?`+${item.atkBoost} attack`:item.type}</small><button type="button" data-testid="clearing-shop-purchase" disabled={busy||essence<item.essencePrice} onClick={()=>setPending(item)} className="mt-auto flex min-h-10 items-center justify-center gap-1 rounded-lg bg-amber-500 px-2 font-black text-emerald-950 disabled:opacity-40"><img src={currencyAssets.essenceToken} alt="" className="h-5 w-5"/>{item.essencePrice}</button></article>)}</div>}
    </section>
    {pending&&<div className="absolute inset-0 flex items-center justify-center bg-black/65 p-6"><div className="w-full max-w-xs rounded-xl border border-amber-400 bg-emerald-950 p-5 text-center"><p>Buy <b>{pending.name}</b> for {pending.essencePrice} Essence?</p><div className="mt-4 flex gap-2"><button type="button" className="flex-1 rounded bg-stone-700 p-2" onClick={()=>setPending(null)}>Cancel</button><button type="button" disabled={busy} className="flex-1 rounded bg-amber-400 p-2 font-bold text-emerald-950" onClick={()=>void confirm()}>Buy</button></div></div></div>}
  </div>;
}
