import { useMemo, useState, type ReactNode } from "react";
import { Plus, Search, Trash2, X } from "lucide-react";
import { itemTypeLabel, itemTypeOptions } from "@/lib/itemTypeFilters";

export type ClearingAdminTab="drops"|"enemies"|"special-mobs"|"shop";
export type ClearingConfig={drops:any[];enemies:any[];specialMobs:any[];missingEnemies:boolean;hasBossWithoutRare:boolean};
type Request={method:string;url:string;body?:unknown;success:string};
type Act=(request:Request)=>void;
const card="rounded-2xl border border-amber-700/35 bg-gradient-to-b from-[#332516]/90 to-[#17120c]/90 p-4 shadow-lg";
const button="min-h-11 rounded-xl border border-amber-500/60 bg-amber-700 px-4 py-2 text-sm font-black text-amber-50 transition hover:bg-amber-600 disabled:cursor-not-allowed disabled:opacity-50";
const field="min-h-11 w-full rounded-xl border border-amber-700/40 bg-black/35 px-3 text-amber-50 outline-none focus:border-amber-400";

export function ClearingAdminHeader({worlds,selected,selectedName,onWorld,config,shop}:{worlds:{id:string;name:string}[];selected:string;selectedName:string;onWorld:(id:string)=>void;config?:ClearingConfig;shop?:any}){
  const badges=[shop?.enabled?"Portal enabled":"Portal disabled",`${config?.drops.length??0} drops`,`${config?.enemies.length??0} enemies`,`${config?.specialMobs.length??0} special mobs`,`${shop?.items?.length??0} shop items`];
  return <header className={`${card} p-5`}><p className="text-xs font-black uppercase tracking-[.2em] text-amber-400">Elysian Clearing</p><h2 className="mt-1 font-fantasy text-2xl font-black text-amber-100">Clearing Administration</h2><p className="mt-2 max-w-2xl text-sm text-stone-300">Manage each world’s Clearing rewards, encounters, special pets, and Essence shop portal.</p><label className="mt-4 block max-w-md text-sm font-bold text-amber-200">World selector<select aria-label="Clearing world" className={`${field} mt-1`} value={selected} onChange={event=>onWorld(event.target.value)}>{worlds.map(world=><option key={world.id} value={world.id}>{world.name}</option>)}</select></label><p className="mt-3 text-sm">Selected world: <strong className="text-amber-300">{selectedName}</strong></p><div className="mt-3 flex flex-wrap gap-2">{badges.map((badge,index)=><span key={badge} className={`rounded-full border px-2.5 py-1 text-xs font-bold ${index===0&&shop?.enabled?"border-emerald-500/60 bg-emerald-950 text-emerald-200":"border-amber-700/50 bg-black/25 text-amber-100"}`}>{badge}</span>)}</div></header>;
}
export function ClearingAdminTabs({active,onChange}:{active:ClearingAdminTab;onChange:(tab:ClearingAdminTab)=>void}){const tabs:[ClearingAdminTab,string][]=[["drops","Drops"],["enemies","Enemies"],["special-mobs","Special Mobs"],["shop","Shop"]];return <nav aria-label="Clearing administration sections" className="max-w-full overflow-x-auto rounded-xl border border-amber-800/35 bg-black/25 p-1"><div className="flex min-w-max gap-1">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>onChange(id)} aria-current={active===id?"page":undefined} className={`min-h-11 rounded-lg px-4 text-sm font-black transition ${active===id?"bg-gradient-to-b from-amber-600 to-amber-800 text-white shadow":"text-amber-200 hover:bg-amber-950/50"}`}>{label}</button>)}</div></nav>}
export function ClearingAssignmentCard({image,name,details,actions}:{image?:string|null;name:string;details:ReactNode;actions:ReactNode}){return <article className="flex min-w-0 flex-col gap-3 rounded-xl border border-amber-800/35 bg-black/25 p-3 sm:flex-row sm:items-center"><img src={image||""} alt="" className="h-16 w-16 shrink-0 rounded-lg object-contain"/><div className="min-w-0 flex-1"><h4 className="break-words font-black text-amber-100">{name}</h4><div className="mt-1 text-xs leading-5 text-stone-300">{details}</div></div><div className="flex flex-wrap items-center gap-2">{actions}</div></article>}
export function ClearingAddItemModal({title,searchLabel,items,onClose,render}:{title:string;searchLabel:string;items:any[];onClose:()=>void;render:(item:any)=>ReactNode}){
  const [search,setSearch]=useState("");
  const [type,setType]=useState("all");
  const types=useMemo(()=>itemTypeOptions(items),[items]);
  const filtered=useMemo(()=>items.filter(item=>(type==="all"||(item.type||"item")===type)&&item.name?.toLowerCase().includes(search.trim().toLowerCase())),[items,search,type]);
  return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-3 sm:items-center" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="max-h-[85dvh] w-full max-w-2xl overflow-hidden rounded-2xl border border-amber-500/60 bg-[#21170e] shadow-2xl"><div className="flex items-center justify-between border-b border-amber-800/40 p-4"><h3 className="font-fantasy text-xl font-black text-amber-100">{title}</h3><button aria-label="Close" className="flex h-11 w-11 items-center justify-center rounded-xl hover:bg-white/10" onClick={onClose}><X/></button></div><div className="p-4"><label className="text-sm font-bold text-amber-200">{searchLabel}<span className="relative mt-1 block"><Search className="absolute left-3 top-3 h-5 w-5 text-stone-400"/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} className={`${field} pl-10`} /></span></label>{types.length>1&&<div className="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="Filter catalog by item type"><button type="button" aria-pressed={type==="all"} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${type==="all"?"border-amber-300 bg-amber-700 text-white shadow-[0_0_12px_rgba(251,191,36,.25)]":"border-amber-800/60 bg-black/30 text-amber-200"}`} onClick={()=>setType("all")}>All Types</button>{types.map(value=><button key={value} type="button" aria-pressed={type===value} className={`shrink-0 rounded-full border px-3 py-2 text-xs font-black ${type===value?"border-amber-300 bg-amber-700 text-white shadow-[0_0_12px_rgba(251,191,36,.25)]":"border-amber-800/60 bg-black/30 text-amber-200"}`} onClick={()=>setType(value)}>{itemTypeLabel(value)}</button>)}</div>}<p className="mt-2 text-xs text-stone-400">{filtered.length} result{filtered.length===1?"":"s"}{type!=="all"?` · ${itemTypeLabel(type)}`:""}</p><div className="mt-3 max-h-[55dvh] space-y-2 overflow-y-auto pr-1">{filtered.map(render)}{filtered.length===0&&<p className="rounded-xl border border-dashed border-amber-700/40 p-8 text-center text-stone-400">No matching items found.</p>}</div></div></div></div>}
const confirmRemove=(name:string,run:()=>void)=>{if(window.confirm(`Remove ${name} from this Clearing?`))run()};

export function ClearingDropsAdmin({worldId,config,catalog,busy,act}:{worldId:string;config:ClearingConfig;catalog:any[];busy:boolean;act:Act}){const[open,setOpen]=useState(false),assigned=new Set(config.drops.map(item=>item.shop_item_id)),available=catalog.filter(item=>!assigned.has(item.id));return <div className="space-y-4"><section className={card}><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-black text-amber-100">Assigned Drops</h3><p className="text-xs text-stone-400">{config.drops.length} configured</p></div><button className={button} onClick={()=>setOpen(true)}><Plus className="mr-1 inline h-4 w-4"/>Add Drop</button></div><p className="my-3 rounded-lg bg-amber-950/45 p-2 text-xs text-amber-200">Items with 3 stars or higher are automatically forced to an effective <strong>Rare</strong> Clearing rarity.</p><div className="space-y-2">{config.drops.map(drop=><ClearingAssignmentCard key={drop.id} image={drop.image_url} name={drop.name} details={<><span>{drop.type} · {drop.item_world_id||"No original world"} · {drop.star_rarity??0}★</span><br/><strong className="capitalize text-amber-300">Effective: {drop.effective_rarity}</strong></>} actions={<><label className="text-xs font-bold">Clearing rarity<select aria-label={`${drop.name} Clearing rarity`} className="ml-2 min-h-11 rounded-lg bg-black/40 px-2" value={drop.effective_rarity} disabled={busy||Number(drop.star_rarity)>=3} onChange={event=>act({method:"PATCH",url:`/api/admin/clearing/drops/${drop.id}`,body:{rarity:event.target.value},success:`${drop.name} rarity updated.`})}>{["common","uncommon","rare"].map(value=><option key={value}>{value}</option>)}</select></label><button className={`${button} border-red-500/50 bg-red-950`} disabled={busy} onClick={()=>confirmRemove(drop.name,()=>act({method:"DELETE",url:`/api/admin/clearing/drops/${drop.id}`,success:`${drop.name} removed.`}))}><Trash2 className="h-4 w-4"/><span className="sr-only">Remove {drop.name}</span></button></>} />)}{!config.drops.length&&<Empty text="No drops are assigned to this world."/>}</div></section>{open&&<ClearingAddItemModal title="Add a Drop" searchLabel="Search catalog by name" items={available} onClose={()=>setOpen(false)} render={item=><Picker key={item.id} item={item} detail={`${item.type} · ${item.worldId||"No world"} · ${item.starRarity??0}★`} disabled={busy} label="Add" onClick={()=>act({method:"POST",url:`/api/admin/clearing/worlds/${worldId}/drops`,body:{shopItemId:item.id,rarity:Number(item.starRarity)>=3?"rare":"common"},success:`${item.name} added as a drop.`})}/>} />}</div>}
export function ClearingEnemiesAdmin({worldId,config,catalog,busy,act}:{worldId:string;config:ClearingConfig;catalog:any[];busy:boolean;act:Act}){const[open,setOpen]=useState(false),assigned=new Set(config.enemies.map(item=>item.enemy_id)),available=catalog.filter(item=>!assigned.has(item.id)),hasRare=config.drops.some(drop=>drop.effective_rarity==="rare");return <AdminList title="Assigned Enemies" count={config.enemies.length} addLabel="Add Enemy" onAdd={()=>setOpen(true)} empty="No enemies are assigned.">{config.enemies.map(enemy=><ClearingAssignmentCard key={enemy.id} image={enemy.image_url} name={enemy.name} details={enemy.is_boss?"Boss encounter":"Regular encounter"} actions={<><label className="text-xs font-bold">Encounter<select aria-label={`${enemy.name} encounter status`} className="ml-2 min-h-11 rounded-lg bg-black/40 px-2" value={enemy.is_boss?"boss":"regular"} disabled={busy} onChange={event=>act({method:"PATCH",url:`/api/admin/clearing/enemies/${enemy.id}`,body:{isBoss:event.target.value==="boss"},success:`${enemy.name} updated.`})}><option value="regular">Regular</option><option value="boss" disabled={!hasRare}>Boss</option></select></label><button className={`${button} border-red-500/50 bg-red-950`} disabled={busy} onClick={()=>confirmRemove(enemy.name,()=>act({method:"DELETE",url:`/api/admin/clearing/enemies/${enemy.id}`,success:`${enemy.name} removed.`}))}><Trash2 className="h-4 w-4"/></button></>}/>)}{!hasRare&&<p className="rounded-lg border border-amber-600/50 bg-amber-950/40 p-3 text-xs text-amber-100">Configure an effective Rare drop before enabling a boss.</p>}{open&&<ClearingAddItemModal title="Add Enemy" searchLabel="Search enemies by name" items={available} onClose={()=>setOpen(false)} render={enemy=><Picker key={enemy.id} item={enemy} detail="Added as a Regular enemy" disabled={busy} label="Add" onClick={()=>act({method:"POST",url:`/api/admin/clearing/worlds/${worldId}/enemies`,body:{enemyId:enemy.id,isBoss:false},success:`${enemy.name} added.`})}/>}/>}</AdminList>}
export function ClearingSpecialMobsAdmin({worldId,config,catalog,busy,act}:{worldId:string;config:ClearingConfig;catalog:any[];busy:boolean;act:Act}){const[open,setOpen]=useState(false),assigned=new Set(config.specialMobs.map(item=>item.pet_shop_item_id)),available=catalog.filter(item=>item.type==="pet"&&!assigned.has(item.id));return <AdminList title="Assigned Special Mobs" count={config.specialMobs.length} addLabel="Add Special Mob" onAdd={()=>setOpen(true)} empty="No special mobs are assigned.">{config.specialMobs.map(pet=><ClearingAssignmentCard key={pet.id} image={pet.hatched_image_url||pet.image_url||pet.egg_image_url} name={pet.name} details={`${Math.max(1,Number(pet.rarity||pet.star_rarity||1))}★ rarity`} actions={<button className={`${button} border-red-500/50 bg-red-950`} disabled={busy} onClick={()=>confirmRemove(pet.name,()=>act({method:"DELETE",url:`/api/admin/clearing/special-mobs/${pet.id}`,success:`${pet.name} removed.`}))}><Trash2 className="h-4 w-4"/></button>}/>)}<p className="text-xs text-amber-100/75">Special mobs retain their existing rare appearance and guaranteed egg-drop behavior.</p>{open&&<ClearingAddItemModal title="Add Special Mob" searchLabel="Search pets by name" items={available} onClose={()=>setOpen(false)} render={pet=><Picker key={pet.id} item={{...pet,imageUrl:pet.hatchedImageUrl||pet.imageUrl||pet.eggImageUrl}} detail={`${Math.max(1,Number(pet.rarity||pet.starRarity||1))}★ rarity`} disabled={busy} label="Add" onClick={()=>act({method:"POST",url:`/api/admin/clearing/worlds/${worldId}/special-mobs`,body:{petShopItemId:pet.id},success:`${pet.name} added.`})}/>}/>}</AdminList>}
function AdminList({title,count,addLabel,onAdd,empty,children}:{title:string;count:number;addLabel:string;onAdd:()=>void;empty:string;children:ReactNode}){return <section className={card}><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-lg font-black text-amber-100">{title}</h3><p className="text-xs text-stone-400">{count} configured</p></div><button className={button} onClick={onAdd}><Plus className="mr-1 inline h-4 w-4"/>{addLabel}</button></div><div className="space-y-2">{count?children:<><Empty text={empty}/>{children}</>}</div></section>}
function Picker({item,detail,disabled,label,onClick}:{item:any;detail:string;disabled:boolean;label:string;onClick:()=>void}){return <div className="flex items-center gap-3 rounded-xl border border-amber-800/35 bg-black/25 p-3"><img src={item.imageUrl||""} alt="" className="h-14 w-14 shrink-0 object-contain"/><div className="min-w-0 flex-1"><strong className="break-words text-amber-100">{item.name}</strong><p className="text-xs text-stone-400">{detail}</p></div><button className={button} disabled={disabled} onClick={onClick}>{label}</button></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-amber-700/40 p-7 text-center text-sm text-stone-400">{text}</p>}
