import { useEffect,useMemo,useState } from "react";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Backpack,Sword,Shield,Gem,Lock,Check,X } from "lucide-react";
import { CLEARING_EQUIPMENT_SALE_VALUES, type ClearingEquipmentSlot, type ClearingInventoryItem, type ClearingLoadoutResponse } from "@shared/clearingEquipment";
import { CLEARING_DROP_RARITY_STYLES } from "@/lib/clearingRarityStyles";
import popupTexture from "@assets/uploads/ClearingEquipPopUp.png";
import bagImage from "@assets/icon_bag.png";
import { currencyAssets } from "@/lib/currencyAssets";

const slots:ClearingEquipmentSlot[]=["weapon","armor","charm"];
const Stars=({item}:{item:ClearingInventoryItem})=><span style={{color:CLEARING_DROP_RARITY_STYLES[item.stars as 1].color}}>{"★".repeat(item.stars)}</span>;
const Stats=({item}:{item:ClearingInventoryItem})=><span className="text-[11px] text-emerald-100">ATK +{item.atkBonus} · DEF +{item.defBonus} · HP +{item.hpBonus}</span>;

export function ClearingHudControls({petImage,onLoadout,onInventory}:{petImage?:string|null;onLoadout:()=>void;onInventory:()=>void}){return <div className="absolute pointer-events-auto flex gap-2" style={{left:14,top:"max(58px, calc(env(safe-area-inset-top, 0px) + 58px))",zIndex:18}}><button data-interactive aria-label="Open Clearing Loadout" onClick={onLoadout} className="h-12 w-12 overflow-hidden rounded-full border-2 border-amber-300 bg-emerald-950 shadow-lg">{petImage?<img src={petImage} alt="" className="h-full w-full object-contain"/>:<Sword className="m-auto text-amber-200"/>}</button><button data-interactive aria-label="Open Clearing Inventory" onClick={onInventory} className="h-12 w-12 rounded-full border-2 border-amber-300 bg-emerald-950 text-amber-100 shadow-lg"><Backpack className="m-auto"/></button></div>}

export function ClearingLoadoutPanel({open,onOpenChange,pet,loadout,onUnequip,onEmpty}:{open:boolean;onOpenChange:(v:boolean)=>void;pet:any;loadout?:ClearingLoadoutResponse;onUnequip:(s:ClearingEquipmentSlot)=>void;onEmpty:(s:ClearingEquipmentSlot)=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] w-[94vw] max-w-md overflow-y-auto border-amber-600 bg-emerald-950 text-amber-50"><DialogHeader><DialogTitle>Clearing Loadout</DialogTitle></DialogHeader><div className="flex items-center gap-3"><div className="h-16 w-16 rounded-full border border-amber-300 bg-black/20">{pet?.imageUrl&&<img src={pet.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div><b>{pet?.petNickname||pet?.name||"Active Pet"}</b><div className="text-xs text-emerald-200">Player-owned loadout</div></div></div>{slots.map(slot=>{const item=loadout?.[slot];const Icon=slot==="weapon"?Sword:slot==="armor"?Shield:Gem;return <div key={slot} className="rounded-xl border border-amber-700/60 bg-black/20 p-3"><div className="mb-2 flex items-center gap-2 capitalize"><Icon size={17}/><b>{slot}</b></div>{item?<div className="flex items-center gap-3"><div className="h-12 w-12">{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0 flex-1"><div className="truncate">{item.name}</div><Stars item={item}/><br/><Stats item={item}/></div><button onClick={()=>onUnequip(slot)} className="rounded-lg border border-amber-500 px-2 py-1 text-xs">Unequip</button></div>:<button onClick={()=>onEmpty(slot)} className="w-full rounded-lg border border-dashed border-emerald-500 p-3 text-emerald-200">Empty — choose {slot}</button>}</div>})}<div className="rounded-xl bg-emerald-900/70 p-3 text-sm"><b>Total equipment:</b> ATK +{loadout?.totals.atk??0} · DEF +{loadout?.totals.def??0} · HP +{loadout?.totals.hp??0}<hr className="my-2 border-emerald-700"/><b>Effective Clearing stats:</b> {loadout?.effectiveStats?`ATK ${loadout.effectiveStats.atk} · DEF ${loadout.effectiveStats.def} · HP ${loadout.effectiveStats.hp}`:"No active pet"}</div></DialogContent></Dialog>}

export function ClearingInventoryPanel({open,onOpenChange,items=[],onEquip,onSell}:{open:boolean;onOpenChange:(v:boolean)=>void;items?:ClearingInventoryItem[];loadout?:ClearingLoadoutResponse;initialSlot?:ClearingEquipmentSlot|null;onEquip:(id:string)=>void;onSell:(ids:string[])=>Promise<unknown>}){
 const [filter]=useState<"all"|ClearingEquipmentSlot>("all"),[sellMode,setSellMode]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[confirm,setConfirm]=useState(false),[detail,setDetail]=useState<ClearingInventoryItem|null>(null),[pending,setPending]=useState(false),[gain,setGain]=useState<number|null>(null);
 useEffect(()=>setSelected(current=>new Set([...current].filter(id=>items.some(item=>item.inventoryId===id&&item.eligibleForSale)))),[items]);
 const shown=useMemo(()=>items.filter(i=>filter==="all"||i.slot===filter).sort((a,b)=>Number(b.equipped)-Number(a.equipped)||b.stars-a.stars),[items,filter]);
 const chosen=items.filter(i=>selected.has(i.inventoryId)),total=chosen.reduce((n,i)=>n+(CLEARING_EQUIPMENT_SALE_VALUES[i.stars as keyof typeof CLEARING_EQUIPMENT_SALE_VALUES]??0)*i.quantity,0);
 const toggle=(item:ClearingInventoryItem)=>{if(!item.eligibleForSale)return;setSelected(current=>{const next=new Set(current);next.has(item.inventoryId)?next.delete(item.inventoryId):next.add(item.inventoryId);return next})};
 const selectEligible=(maxStars=5)=>setSelected(new Set(items.filter(i=>i.eligibleForSale&&i.stars<=maxStars).map(i=>i.inventoryId)));
 const close=()=>{setSellMode(false);setSelected(new Set());setConfirm(false);setDetail(null);onOpenChange(false)};
 return <Dialog open={open} onOpenChange={v=>{if(!v)close()}}><DialogContent aria-describedby={undefined} className="max-h-[92dvh] w-[96vw] max-w-md overflow-y-auto border-4 border-amber-500 bg-[#123f2c] p-3 text-amber-50 shadow-[inset_0_0_0_2px_#6b451d,0_12px_30px_#000] [&>button.absolute]:hidden" style={{backgroundImage:`linear-gradient(rgba(5,46,34,.78),rgba(5,46,34,.92)),url(${popupTexture})`,backgroundSize:"cover"}}><DialogHeader className="flex-row items-center gap-2 border-b border-amber-500/60 pb-2"><img src={bagImage} alt="" className="h-11 w-11 object-contain"/><DialogTitle className="flex-1 font-serif text-2xl text-amber-200">Clearing Gear</DialogTitle><button aria-label="Close Clearing Gear" onClick={close} className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-amber-300 bg-red-900"><X/></button></DialogHeader>
 <div className="flex items-center justify-between gap-2"><button onClick={()=>{setSellMode(v=>!v);setSelected(new Set());setDetail(null)}} className="min-h-11 rounded-lg border-2 border-amber-400 bg-amber-700 px-4 font-black">{sellMode?"Cancel":"Sell Gear"}</button>{sellMode&&<div className="flex flex-wrap justify-end gap-1">{[[1,"Choose 1★"],[2,"Choose 1–2★"],[5,"Choose All"]].map(([n,label])=><button key={String(label)} onClick={()=>selectEligible(Number(n))} className="min-h-9 rounded-md border border-amber-500 bg-emerald-900 px-2 text-[11px]">{label}</button>)}<button onClick={()=>setSelected(new Set())} className="min-h-9 rounded-md border border-amber-500 bg-emerald-900 px-2 text-[11px]">Clear</button></div>}</div>
 {!shown.length?<div className="py-12 text-center text-emerald-200"><Backpack className="mx-auto mb-3"/>Clearing Equipment can be found by defeating enemies in Clearings.</div>:<div data-testid="clearing-inventory-grid" className="grid grid-cols-3 gap-2 min-[410px]:grid-cols-4">{shown.map(item=>{const locked=!item.eligibleForSale,selectedNow=selected.has(item.inventoryId),Icon=item.slot==="weapon"?Sword:item.slot==="armor"?Shield:Gem;return <button key={item.inventoryId} aria-label={`${item.name}${locked?", locked":""}`} aria-pressed={sellMode?selectedNow:undefined} title={locked?item.equipped?"Equipped gear cannot be sold":"Protected, listed, starter, or otherwise ineligible gear cannot be sold":item.name} onClick={()=>sellMode?toggle(item):setDetail(item)} disabled={sellMode&&locked} className={`relative aspect-square min-w-0 rounded-lg p-2 transition-all disabled:opacity-35 ${sellMode?(selectedNow?"bg-emerald-800/60 ring-2 ring-amber-200":"bg-transparent hover:bg-white/5"):"bg-black/20"}`} style={sellMode?undefined:{boxShadow:`inset 0 0 16px ${CLEARING_DROP_RARITY_STYLES[item.stars as 1].color}55`}}>{item.imageUrl&&<img src={item.imageUrl} alt="" className={`${sellMode?"h-full":"h-[68%]"} w-full object-contain ${sellMode&&!selectedNow?"opacity-80":"opacity-100"}`}/>} {!sellMode&&<><span className="absolute bottom-1 left-1 text-[10px]"><Icon size={13}/></span><span className="absolute bottom-1 left-1/2 -translate-x-1/2 whitespace-nowrap text-[10px]"><Stars item={item}/></span>{(locked||item.equipped)&&<span className="absolute left-1 top-1 rounded bg-emerald-950/90 p-1"><Lock size={12}/></span>}{item.equipped&&<span className="absolute inset-x-1 top-1/2 bg-amber-500/90 text-center text-[9px] font-black text-black">EQUIPPED</span>}</>}{!sellMode&&item.quantity>1&&<span className="absolute right-1 top-1 rounded bg-black/80 px-1 text-xs">×{item.quantity}</span>}{selectedNow&&<span className="absolute right-1 top-1 rounded-full bg-amber-200 p-1 text-emerald-950 shadow"><Check size={14}/></span>}</button>})}</div>}
 {detail&&!sellMode&&<div data-testid="clearing-item-detail" className="rounded-xl border-2 border-amber-400 bg-emerald-950/95 p-3"><div className="flex gap-3"><div className="h-24 w-24 rounded-lg border border-amber-600 bg-black/20 p-2">{detail.imageUrl&&<img src={detail.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0"><h3 className="font-serif text-lg text-amber-200">{detail.name}</h3><Stars item={detail}/><div className="capitalize">{detail.slot}</div><Stats item={detail}/>{detail.eligibleForSale&&<div className="mt-1 flex items-center gap-1"><img src={currencyAssets.essenceToken} alt="Essence" className="h-5 w-5"/>{CLEARING_EQUIPMENT_SALE_VALUES[detail.stars as 1]*detail.quantity}</div>}</div></div><button disabled={detail.equipped} onClick={()=>onEquip(detail.inventoryId)} className="mt-3 min-h-11 w-full rounded-lg bg-amber-400 font-black text-emerald-950 disabled:bg-emerald-700 disabled:text-white">{detail.equipped?"Equipped":"Equip"}</button></div>}
 {sellMode&&<div className="sticky bottom-0 z-10 rounded-xl border-2 border-amber-400 bg-emerald-950/95 p-2 shadow-lg"><div className="flex items-center gap-2"><div className="flex min-w-0 flex-1 -space-x-2">{chosen.slice(0,4).map(i=><img key={i.inventoryId} src={i.imageUrl||bagImage} alt="" className="h-8 w-8 rounded border border-amber-400 bg-emerald-900 object-contain"/>)}</div><b>{chosen.reduce((n,i)=>n+i.quantity,0)} selected</b><span className="flex items-center gap-1 font-black text-amber-200"><img src={currencyAssets.essenceToken} alt="Essence" className="h-6 w-6"/>{total}</span></div><button disabled={!selected.size} onClick={()=>setConfirm(true)} className="mt-2 min-h-12 w-full rounded-lg bg-amber-400 font-black text-emerald-950 disabled:opacity-50">Sell for {total}</button></div>}
 {confirm&&<div role="alertdialog" aria-modal="true" aria-labelledby="trade-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-5"><div className="w-full max-w-sm rounded-2xl border-4 border-amber-500 bg-emerald-950 p-5 text-center"><h3 id="trade-title" className="font-serif text-2xl text-amber-200">Trade Gear?</h3><div className="my-3 grid grid-cols-4 gap-2">{chosen.slice(0,8).map(i=><img key={i.inventoryId} src={i.imageUrl||bagImage} alt="" className="aspect-square w-full rounded border border-amber-500 object-contain"/>)}</div><p>{chosen.reduce((n,i)=>n+i.quantity,0)} items</p><p className="flex items-center justify-center gap-1 text-xl font-black"><img src={currencyAssets.essenceToken} alt="Essence" className="h-7 w-7"/>{total}</p><p className="my-3 text-sm text-red-200">Sold equipment cannot be recovered.</p><div className="flex gap-2"><button disabled={pending} className="min-h-12 flex-1 rounded border border-amber-500" onClick={()=>setConfirm(false)}>Keep Gear</button><button disabled={pending} className="min-h-12 flex-1 rounded bg-amber-400 font-bold text-emerald-950 disabled:opacity-50" onClick={async()=>{setPending(true);try{await onSell([...selected]);setConfirm(false);setSelected(new Set());setSellMode(false);setGain(total);setTimeout(()=>setGain(null),1800)}finally{setPending(false)}}}>{pending?"Trading…":"Trade"}</button></div></div></div>}{gain!==null&&<div aria-live="polite" className="fixed left-1/2 top-24 z-[60] -translate-x-1/2 rounded-full bg-amber-400 px-4 py-2 font-black text-emerald-950">+{gain} Essence</div>}
 </DialogContent></Dialog>
}
