import { useMemo,useState } from "react";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Backpack,Sword,Shield,Gem } from "lucide-react";
import { CLEARING_EQUIPMENT_SALE_VALUES, type ClearingEquipmentSlot, type ClearingInventoryItem, type ClearingLoadoutResponse } from "@shared/clearingEquipment";
import { CLEARING_DROP_RARITY_STYLES } from "@/lib/clearingRarityStyles";

const slots:ClearingEquipmentSlot[]=["weapon","armor","charm"];
const Stars=({item}:{item:ClearingInventoryItem})=><span style={{color:CLEARING_DROP_RARITY_STYLES[item.stars as 1].color}}>{"★".repeat(item.stars)}</span>;
const Stats=({item}:{item:ClearingInventoryItem})=><span className="text-[11px] text-emerald-100">ATK +{item.atkBonus} · DEF +{item.defBonus} · HP +{item.hpBonus}</span>;

export function ClearingHudControls({petImage,onLoadout,onInventory}:{petImage?:string|null;onLoadout:()=>void;onInventory:()=>void}){return <div className="absolute pointer-events-auto flex gap-2" style={{left:14,top:"max(58px, calc(env(safe-area-inset-top, 0px) + 58px))",zIndex:18}}><button data-interactive aria-label="Open Clearing Loadout" onClick={onLoadout} className="h-12 w-12 overflow-hidden rounded-full border-2 border-amber-300 bg-emerald-950 shadow-lg">{petImage?<img src={petImage} alt="" className="h-full w-full object-contain"/>:<Sword className="m-auto text-amber-200"/>}</button><button data-interactive aria-label="Open Clearing Inventory" onClick={onInventory} className="h-12 w-12 rounded-full border-2 border-amber-300 bg-emerald-950 text-amber-100 shadow-lg"><Backpack className="m-auto"/></button></div>}

export function ClearingLoadoutPanel({open,onOpenChange,pet,loadout,onUnequip,onEmpty}:{open:boolean;onOpenChange:(v:boolean)=>void;pet:any;loadout?:ClearingLoadoutResponse;onUnequip:(s:ClearingEquipmentSlot)=>void;onEmpty:(s:ClearingEquipmentSlot)=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] w-[94vw] max-w-md overflow-y-auto border-amber-600 bg-emerald-950 text-amber-50"><DialogHeader><DialogTitle>Clearing Loadout</DialogTitle></DialogHeader><div className="flex items-center gap-3"><div className="h-16 w-16 rounded-full border border-amber-300 bg-black/20">{pet?.imageUrl&&<img src={pet.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div><b>{pet?.petNickname||pet?.name||"Active Pet"}</b><div className="text-xs text-emerald-200">Player-owned loadout</div></div></div>{slots.map(slot=>{const item=loadout?.[slot];const Icon=slot==="weapon"?Sword:slot==="armor"?Shield:Gem;return <div key={slot} className="rounded-xl border border-amber-700/60 bg-black/20 p-3"><div className="mb-2 flex items-center gap-2 capitalize"><Icon size={17}/><b>{slot}</b></div>{item?<div className="flex items-center gap-3"><div className="h-12 w-12">{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0 flex-1"><div className="truncate">{item.name}</div><Stars item={item}/><br/><Stats item={item}/></div><button onClick={()=>onUnequip(slot)} className="rounded-lg border border-amber-500 px-2 py-1 text-xs">Unequip</button></div>:<button onClick={()=>onEmpty(slot)} className="w-full rounded-lg border border-dashed border-emerald-500 p-3 text-emerald-200">Empty — choose {slot}</button>}</div>})}<div className="rounded-xl bg-emerald-900/70 p-3 text-sm"><b>Total equipment:</b> ATK +{loadout?.totals.atk??0} · DEF +{loadout?.totals.def??0} · HP +{loadout?.totals.hp??0}<hr className="my-2 border-emerald-700"/><b>Effective Clearing stats:</b> {loadout?.effectiveStats?`ATK ${loadout.effectiveStats.atk} · DEF ${loadout.effectiveStats.def} · HP ${loadout.effectiveStats.hp}`:"No active pet"}</div></DialogContent></Dialog>}

export function ClearingInventoryPanel({open,onOpenChange,items=[],onEquip,onSell}:{open:boolean;onOpenChange:(v:boolean)=>void;items?:ClearingInventoryItem[];loadout?:ClearingLoadoutResponse;initialSlot?:ClearingEquipmentSlot|null;onEquip:(id:string)=>void;onSell:(ids:string[])=>Promise<unknown>}){
 // Item stats remain visible to Compare with the equipped slot before onEquip; onUnequip stays in the loadout panel.
 const [filter,setFilter]=useState<"all"|ClearingEquipmentSlot>("all"),[sellMode,setSellMode]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[confirm,setConfirm]=useState(false);
 const shown=useMemo(()=>items.filter(i=>filter==="all"||i.slot===filter).sort((a,b)=>Number(b.equipped)-Number(a.equipped)||b.stars-a.stars),[items,filter]);
 const chosen=items.filter(i=>selected.has(i.inventoryId)),total=chosen.reduce((n,i)=>n+(CLEARING_EQUIPMENT_SALE_VALUES[i.stars as keyof typeof CLEARING_EQUIPMENT_SALE_VALUES]??0)*i.quantity,0);
 const toggle=(item:ClearingInventoryItem)=>{if(!item.eligibleForSale)return;setSelected(current=>{const next=new Set(current);next.has(item.inventoryId)?next.delete(item.inventoryId):next.add(item.inventoryId);return next})};
 const selectEligible=(maxStars=5)=>setSelected(new Set(items.filter(i=>i.eligibleForSale&&i.stars<=maxStars).map(i=>i.inventoryId)));
 return <Dialog open={open} onOpenChange={v=>{if(!v){setSellMode(false);setSelected(new Set());setConfirm(false)}onOpenChange(v)}}><DialogContent className="max-h-[88dvh] w-[94vw] max-w-md overflow-y-auto border-amber-600 bg-emerald-950 text-amber-50"><DialogHeader><DialogTitle>Clearing Inventory</DialogTitle></DialogHeader><div className="flex flex-wrap gap-1">{(["all",...slots] as const).map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-full px-3 py-1 text-xs capitalize ${filter===s?"bg-amber-500 text-black":"bg-emerald-800"}`}>{s}</button>)}<button onClick={()=>{setSellMode(v=>!v);setSelected(new Set())}} className="ml-auto rounded-full border border-amber-400 px-3 py-1 text-xs">{sellMode?"Cancel Sale":"Select to Sell"}</button></div>
 {sellMode&&<div className="rounded-xl border border-amber-700 bg-emerald-900/80 p-2 text-xs"><b>{chosen.reduce((n,i)=>n+i.quantity,0)} selected · {total} essence</b><div className="mt-2 flex flex-wrap gap-1"><button onClick={()=>selectEligible(1)} className="rounded bg-emerald-700 px-2 py-1">All 1★</button><button onClick={()=>selectEligible(2)} className="rounded bg-emerald-700 px-2 py-1">All 1–2★</button><button onClick={()=>selectEligible()} className="rounded bg-amber-600 px-2 py-1">Sell All eligible</button></div></div>}
 {!shown.length?<div className="py-12 text-center text-emerald-200"><Backpack className="mx-auto mb-3"/>Clearing Equipment can be found by defeating enemies in Clearings.</div>:<div className="grid gap-2">{shown.map(item=><button key={item.inventoryId} onClick={()=>sellMode?toggle(item):onEquip(item.inventoryId)} disabled={sellMode&&!item.eligibleForSale} className={`relative flex items-center gap-3 rounded-xl border p-2 text-left disabled:opacity-45 ${selected.has(item.inventoryId)?"border-amber-300 bg-amber-500/20":"border-emerald-700"}`}><div className="h-12 w-12 shrink-0">{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0 flex-1"><b className="block truncate">{item.name} {item.quantity>1&&`×${item.quantity}`}</b><span className="capitalize text-xs">{item.slot} {item.equipped&&"· Equipped"}</span><br/><Stars item={item}/><br/><Stats item={item}/></div>{selected.has(item.inventoryId)&&<span className="text-xl text-amber-300">✓</span>}</button>)}</div>}
 {sellMode&&selected.size>0&&<button onClick={()=>setConfirm(true)} className="sticky bottom-0 w-full rounded-lg bg-amber-400 py-2 font-bold text-emerald-950">Review Sale</button>}
 {confirm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-5"><div className="max-w-sm rounded-2xl border-2 border-amber-500 bg-emerald-950 p-5 text-center"><h3 className="font-serif text-xl text-amber-200">Confirm Equipment Sale</h3><p className="my-3">Sell {chosen.reduce((n,i)=>n+i.quantity,0)} items for <b>{total} essence</b>?</p><p className="text-sm text-red-200">Sold equipment cannot be recovered.</p><div className="mt-4 flex gap-2"><button className="flex-1 rounded border border-amber-500 py-2" onClick={()=>setConfirm(false)}>Go Back</button><button className="flex-1 rounded bg-amber-400 py-2 font-bold text-emerald-950" onClick={async()=>{await onSell([...selected]);setConfirm(false);setSelected(new Set());setSellMode(false)}}>Sell</button></div></div></div>}
 </DialogContent></Dialog>
}
