import { useMemo,useState } from "react";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Backpack,Sword,Shield,Gem } from "lucide-react";
import type { ClearingEquipmentSlot,ClearingInventoryItem,ClearingLoadoutResponse } from "@shared/clearingEquipment";
import { CLEARING_DROP_RARITY_STYLES } from "@/lib/clearingRarityStyles";

const slots:ClearingEquipmentSlot[]=["weapon","armor","charm"];
const Stars=({item}:{item:ClearingInventoryItem})=><span style={{color:CLEARING_DROP_RARITY_STYLES[item.stars as 1].color}}>{"★".repeat(item.stars)}</span>;
const Stats=({item}:{item:ClearingInventoryItem})=><span className="text-[11px] text-emerald-100">ATK +{item.atkBonus} · DEF +{item.defBonus} · HP +{item.hpBonus}</span>;

export function ClearingHudControls({petImage,onLoadout,onInventory}:{petImage?:string|null;onLoadout:()=>void;onInventory:()=>void}){return <div className="absolute pointer-events-auto flex gap-2" style={{left:14,top:"max(58px, calc(env(safe-area-inset-top, 0px) + 58px))",zIndex:18}}><button data-interactive aria-label="Open Clearing Loadout" onClick={onLoadout} className="h-12 w-12 overflow-hidden rounded-full border-2 border-amber-300 bg-emerald-950 shadow-lg">{petImage?<img src={petImage} alt="" className="h-full w-full object-contain"/>:<Sword className="m-auto text-amber-200"/>}</button><button data-interactive aria-label="Open Clearing Inventory" onClick={onInventory} className="h-12 w-12 rounded-full border-2 border-amber-300 bg-emerald-950 text-amber-100 shadow-lg"><Backpack className="m-auto"/></button></div>}

export function ClearingLoadoutPanel({open,onOpenChange,pet,loadout,onUnequip,onEmpty}:{open:boolean;onOpenChange:(v:boolean)=>void;pet:any;loadout?:ClearingLoadoutResponse;onUnequip:(s:ClearingEquipmentSlot)=>void;onEmpty:(s:ClearingEquipmentSlot)=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] w-[94vw] max-w-md overflow-y-auto border-amber-600 bg-emerald-950 text-amber-50"><DialogHeader><DialogTitle>Clearing Loadout</DialogTitle></DialogHeader><div className="flex items-center gap-3"><div className="h-16 w-16 rounded-full border border-amber-300 bg-black/20">{pet?.imageUrl&&<img src={pet.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div><b>{pet?.petNickname||pet?.name||"Active Pet"}</b><div className="text-xs text-emerald-200">Player-owned loadout</div></div></div>{slots.map(slot=>{const item=loadout?.[slot];const Icon=slot==="weapon"?Sword:slot==="armor"?Shield:Gem;return <div key={slot} className="rounded-xl border border-amber-700/60 bg-black/20 p-3"><div className="mb-2 flex items-center gap-2 capitalize"><Icon size={17}/><b>{slot}</b></div>{item?<div className="flex items-center gap-3"><div className="h-12 w-12">{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0 flex-1"><div className="truncate">{item.name}</div><Stars item={item}/><br/><Stats item={item}/></div><button onClick={()=>onUnequip(slot)} className="rounded-lg border border-amber-500 px-2 py-1 text-xs">Unequip</button></div>:<button onClick={()=>onEmpty(slot)} className="w-full rounded-lg border border-dashed border-emerald-500 p-3 text-emerald-200">Empty — choose {slot}</button>}</div>})}<div className="rounded-xl bg-emerald-900/70 p-3 text-sm"><b>Total equipment:</b> ATK +{loadout?.totals.atk??0} · DEF +{loadout?.totals.def??0} · HP +{loadout?.totals.hp??0}<hr className="my-2 border-emerald-700"/><b>Effective Clearing stats:</b> {loadout?.effectiveStats?`ATK ${loadout.effectiveStats.atk} · DEF ${loadout.effectiveStats.def} · HP ${loadout.effectiveStats.hp}`:"No active pet"}</div></DialogContent></Dialog>}

export function ClearingInventoryPanel({open,onOpenChange,items=[],loadout,initialSlot,onEquip}:{open:boolean;onOpenChange:(v:boolean)=>void;items?:ClearingInventoryItem[];loadout?:ClearingLoadoutResponse;initialSlot?:ClearingEquipmentSlot|null;onEquip:(id:string)=>void}){const [filter,setFilter]=useState<"all"|ClearingEquipmentSlot>(initialSlot??"all"),[selected,setSelected]=useState<ClearingInventoryItem|null>(null);const shown=useMemo(()=>items.filter(i=>filter==="all"||i.slot===filter).sort((a,b)=>Number(b.equipped)-Number(a.equipped)||b.stars-a.stars||(b.atkBonus+b.defBonus+b.hpBonus)-(a.atkBonus+a.defBonus+a.hpBonus)||a.name.localeCompare(b.name)),[items,filter]);const current=selected?loadout?.[selected.slot]:null;return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] w-[94vw] max-w-md overflow-y-auto border-amber-600 bg-emerald-950 text-amber-50"><DialogHeader><DialogTitle>Clearing Inventory</DialogTitle></DialogHeader><div className="flex gap-1 overflow-x-auto">{(["all",...slots] as const).map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-full px-3 py-1 text-xs capitalize ${filter===s?"bg-amber-500 text-black":"bg-emerald-800"}`}>{s}</button>)}</div>{!shown.length?<div data-testid="clearing-inventory-empty" className="py-12 text-center text-emerald-200"><Backpack className="mx-auto mb-3"/>Clearing Equipment can be found by defeating enemies in Clearings.</div>:<div className="grid grid-cols-1 gap-2">{shown.map(item=><button key={item.inventoryId} onClick={()=>setSelected(item)} className={`flex items-center gap-3 rounded-xl border p-2 text-left ${selected?.inventoryId===item.inventoryId?"border-amber-300":"border-emerald-700"}`}><div className="h-12 w-12 shrink-0">{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-full w-full object-contain"/>}</div><div className="min-w-0 flex-1"><b className="block truncate">{item.name} {item.quantity>1&&`×${item.quantity}`}</b><span className="capitalize text-xs">{item.slot} {item.equipped&&"· Equipped"}</span><br/><Stars item={item}/><br/><Stats item={item}/></div></button>)}</div>}{selected&&<div className="sticky bottom-0 rounded-xl border border-amber-600 bg-emerald-900 p-3"><b>Compare with {current?.name??"empty slot"}</b>{(["atkBonus","defBonus","hpBonus"] as const).map((key,i)=>{const delta=selected[key]-(current?.[key]??0);return <span key={key} className={`ml-2 text-xs ${delta>0?"text-green-300":delta<0?"text-red-300":"text-slate-300"}`}>{["ATK","DEF","HP"][i]} {delta>=0?"+":""}{delta}</span>})}<button disabled={selected.equipped} onClick={()=>onEquip(selected.inventoryId)} className="mt-3 w-full rounded-lg bg-amber-400 py-2 font-bold text-emerald-950 disabled:opacity-50">{selected.equipped?"Equipped":"Equip"}</button></div>}</DialogContent></Dialog>}
