import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useQuery } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { ELYSIAN_CLEARING_COMBAT_CONFIG as CFG } from "@/lib/elysianClearingCombatConfig";
import type { PetWalkPos } from "@/hooks/usePetWalkController";
import { Sword } from "lucide-react";
import skullUrl from "@assets/Photoroom_20260705_103527_PM_1783308939570.png";
import { clampPoint, directionToClearingTarget, nearestValidClearingTarget, pixelDelta, pixelDistance, stepToward, type WorldPixels } from "@/lib/elysianClearingCombatMath";
import { useClearingEquipment } from "@/hooks/useClearingEquipment";
import ClearingEquipmentModal from "@/components/ClearingEquipmentModal";
import { ClearingInventoryPanel } from "@/components/ClearingEquipmentPanels";
import { currencyAssets } from "@/lib/currencyAssets";
import fallbackPet from "@assets/logo_parapets.png";
import { usePlayerCurrencyBalances } from "@/hooks/usePlayerCurrencyBalances";
import { enemyFlipScale, nextEnemyFacing } from "@shared/clearingCombat";
import type { ClearingLoadout } from "@shared/clearingEquipment";
import ClearingAttackEffect from "@/components/ClearingAttackEffect";
import { CLEARING_SWORD_TIMING, type ClearingAttackPhase } from "@/lib/clearingWeaponVisuals";
import { clearingWeaponOrigin, CLEARING_PET_PRESENTATION } from "@/lib/clearingPetPresentation";
import type { ClearingRewardChest } from "@shared/clearingEquipment";
import { ClearingChestLayer } from "@/components/ClearingRewardChests";
import { CLEARING_WORLD_LAYERS, worldYToDepth } from "@/lib/clearingWorldPresentation";
import { clusterHomes, enemyVisibleHeight, engageConfirmedEnemy, resetEnemyPassive, resolveEnemyPairs } from "@/lib/clearingEnemyBehavior";
import { FALLBACK_ENEMY_IMAGE_METRICS, loadEnemyImageMetrics, type EnemyImageMetrics } from "@/lib/enemyImageMetrics";
import { resolveClearingAttackStyle } from "@shared/clearingCombat";

type EnemyState = "spawning" | "roaming" | "pursuing" | "windup" | "recovering" | "returning" | "defeated" | "respawning";
type Enemy = { instanceId:string; slot:number; maxHealth:number; health:number; attack:number; isBoss:boolean; engagedByPlayer:boolean; templateId?:string; name?:string; imageUrl?:string|null; x:number; y:number; homeX:number; homeY:number; targetX:number; targetY:number; state:EnemyState; facingLeft:boolean; nextActionAt:number; visibleHalfWidth:number };
type EnemyDeathEffect = { effectId:string; enemyInstanceId:string; x:number; y:number; exp:number };
type Session = { sessionId:string; loadout:ClearingLoadout; pet:{inventoryId:string;maxHealth:number;attack:number}; enemies:Array<Omit<Enemy,"x"|"y"|"targetX"|"targetY"|"state"|"facingLeft"|"nextActionAt">>; chests:ClearingRewardChest[];eggDrops:SpecialEggDrop[] };
type SpecialEggDrop={id:string;petShopItemId:string;name:string;eggImageUrl:string|null;stars:number;worldX:number;worldY:number};
type ClearingPotion = { inventoryId:string; shopItemId:string; name:string; imageUrl:string|null; quantity:number; healthRestored:number; manaRestored:number };

const randomBetween = (a:number,b:number) => a + Math.random()*(b-a);
let activeClearingLoops = 0;

export default function ElysianClearingCombat({ petPos, petSize, activePet, facingLeft, onReturnToWorld, worldPixels, hudElement, onGameplayBlockedChange }: { petPos:PetWalkPos; petSize:number; activePet?:any; facingLeft:boolean; onReturnToWorld:()=>void; worldPixels:WorldPixels; hudElement:HTMLElement|null; onGameplayBlockedChange:(blocked:boolean)=>void }) {
  const petPosRef = useRef(petPos); petPosRef.current = petPos;
  const [session, setSession] = useState<Session|null>(null);
  const [sessionState,setSessionState]=useState<"loading"|"ready"|"error">("loading");
  const [sessionAttempt,setSessionAttempt]=useState(0);
  const [enemies, setEnemies] = useState<Enemy[]>([]);
  const [imageMetrics,setImageMetrics]=useState<Record<string,EnemyImageMetrics>>({});
  const enemiesRef = useRef<Enemy[]>([]);
  const [petHealth,setPetHealth] = useState(1); const [petMaxHealth,setPetMaxHealth] = useState(1);
  const [recentlyDamaged,setRecentlyDamaged] = useState(false); const recentDamageTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [deathEffects,setDeathEffects] = useState<EnemyDeathEffect[]>([]); const effectSequence=useRef(0);
  const petHealthRef=useRef(1); const petMaxHealthRef=useRef(1); const invulnerableUntil=useRef(0); const defeatedUntil=useRef(0); const timers=useRef<Set<ReturnType<typeof setTimeout>>>(new Set());
  const lastAttack=useRef(0); const attackPhaseRef=useRef<ClearingAttackPhase>("idle"); const [attackPhase,setAttackPhaseState]=useState<ClearingAttackPhase>("idle"); const setAttackPhase=(phase:ClearingAttackPhase)=>{attackPhaseRef.current=phase;setAttackPhaseState(phase)}; const [attackFacingLeft,setAttackFacingLeft]=useState(false); const [feedback,setFeedback]=useState<string[]>([]);
  const [attackDirection,setAttackDirection]=useState({angleRadians:0,distance:0});
  const equipment=useClearingEquipment();const balances=usePlayerCurrencyBalances();
  const [chests,setChests]=useState<ClearingRewardChest[]>([]);const [eggDrops,setEggDrops]=useState<SpecialEggDrop[]>([]);const [selectedChest,setSelectedChest]=useState<ClearingRewardChest|null>(null);const [openingChestId,setOpeningChestId]=useState<string|null>(null);const [claimingChest,setClaimingChest]=useState(false);const [chestError,setChestError]=useState<string|null>(null);
  const [equipmentOpen,setEquipmentOpen]=useState(false);const [inventoryOpen,setInventoryOpen]=useState(false);
  const {data:playerInventory=[]}=useQuery<any[]>({queryKey:["/api/inventory"]});
  const availablePotions:ClearingPotion[]=playerInventory.filter(item=>item.type==="potion"&&(Number(item.healthRestored)>0||Number(item.manaRestored)>0)&&Number(item.petsRevived||0)===0).map(item=>({inventoryId:item.inventoryId,shopItemId:item.shopItemId,name:item.name,imageUrl:item.imageUrl,quantity:Math.min(50,Math.max(0,Number(item.quantity||1))),healthRestored:Number(item.healthRestored||0),manaRestored:Number(item.manaRestored||0)}));
  const [potionSlots,setPotionSlots]=useState<(string|null)[]>(()=>{try{const saved=JSON.parse(localStorage.getItem("clearing:potion-slots:v1")||"[]");return [0,1,2].map(index=>typeof saved[index]==="string"?saved[index]:null);}catch{return[null,null,null];}});
  const [potionPickerSlot,setPotionPickerSlot]=useState<number|null>(null);const [usingPotion,setUsingPotion]=useState(false);const usingPotionRef=useRef(false);
  useEffect(()=>{localStorage.setItem("clearing:potion-slots:v1",JSON.stringify(potionSlots));},[potionSlots]);
  const gameplayState: "loading"|"running"|"menu-paused"|"defeated" = sessionState!=="ready" ? "loading" : equipmentOpen||inventoryOpen||potionPickerSlot!==null ? "menu-paused" : petHealth<=0 ? "defeated" : "running";
  const gameplayStateRef=useRef(gameplayState);gameplayStateRef.current=gameplayState;
  const pausedAt=useRef<number|null>(null);
  const sessionStartedAt=useRef(performance.now());

  useEffect(() => {
    onGameplayBlockedChange(equipmentOpen||inventoryOpen||potionPickerSlot!==null||petHealth<=0);
    return () => onGameplayBlockedChange(false);
  }, [equipmentOpen,inventoryOpen,potionPickerSlot,petHealth,onGameplayBlockedChange]);

  useEffect(()=>{const now=performance.now();if(gameplayState==="menu-paused"&&pausedAt.current===null)pausedAt.current=now;else if(gameplayState==="running"&&pausedAt.current!==null){const duration=now-pausedAt.current;for(const enemy of enemiesRef.current)if(Number.isFinite(enemy.nextActionAt))enemy.nextActionAt+=duration+250;lastAttack.current+=duration;pausedAt.current=null;}},[gameplayState]);

  useEffect(()=>{ let alive=true; let createdId=""; setSessionState("loading");
    fetch("/api/explore/elysian-clearing/session",{method:"POST",credentials:"include"}).then(async r=>{const body=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(body.message||"combat session failed"),{code:body.code||`HTTP_${r.status}`,status:r.status});return body}).then((data:Session)=>{
      if(!alive)return; createdId=data.sessionId; setSession(data);setChests(data.chests??[]);setEggDrops(data.eggDrops??[]);queryClient.setQueryData(["/api/clearing/loadout"],data.loadout);void Promise.all([queryClient.invalidateQueries({queryKey:["/api/clearing/inventory"]}),queryClient.invalidateQueries({queryKey:["/api/clearing/loadout"]})]); setSessionState("ready"); setPetHealth(data.pet.maxHealth); setPetMaxHealth(data.pet.maxHealth); petHealthRef.current=data.pet.maxHealth; petMaxHealthRef.current=data.pet.maxHealth;
      const now=performance.now(),source=data.enemies.slice(0,CFG.maxEnemies),grouped=clusterHomes(source,CFG.homes);sessionStartedAt.current=now; const built=source.map((e,i)=>{const h=grouped[i],visibleHeight=enemyVisibleHeight(e.isBoss);return {...e,engagedByPlayer:false,slot:i,x:h.homeX,y:h.homeY,homeX:h.homeX,homeY:h.homeY,targetX:h.homeX,targetY:h.homeY,visibleHalfWidth:visibleHeight*.4,state:"spawning" as EnemyState,facingLeft:false,nextActionAt:now+(CFG.initialSpawnDelayMs[i]??500)}}); enemiesRef.current=built;setEnemies(built);
    }).catch((error:any)=>{if(alive){const code=String(error?.code||(error?.status===401?"CLEARING_AUTH_REQUIRED":"CLEARING_TEMPORARILY_UNAVAILABLE"));setSessionState("error");setFeedback([code==="CLEARING_ACTIVE_PET_REQUIRED"?"Choose an active hatched pet":code==="CLEARING_AUTH_REQUIRED"||code==="HTTP_401"?"Please sign in again":code==="CLEARING_MIGRATION_REQUIRED"?"Clearing update required":"Combat temporarily unavailable"]);} console.error("Elysian Clearing session failed",{code:error?.code??"unknown",status:error?.status});});
    return()=>{alive=false;timers.current.forEach(clearTimeout);timers.current.clear();if(recentDamageTimer.current)clearTimeout(recentDamageTimer.current);if(createdId)void fetch(`/api/explore/elysian-clearing/session/${createdId}`,{method:"DELETE",credentials:"include",keepalive:true}).catch(error=>console.error("Elysian Clearing cleanup failed",error instanceof Error?error.message:"Unknown error"));};
  },[sessionAttempt]);

  useEffect(()=>{let live=true;for(const enemy of enemies){const url=enemy.imageUrl||CFG.enemyImageUrl;if(!imageMetrics[url])void loadEnemyImageMetrics(url).then(metrics=>{if(live)setImageMetrics(current=>current[url]?current:{...current,[url]:metrics});});}return()=>{live=false};},[enemies,imageMetrics]);

  useEffect(()=>{if(!session)return;const timer=setInterval(()=>{void fetch("/api/explore/elysian-clearing/position",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.sessionId,x:petPosRef.current.x,y:petPosRef.current.y})});},500);return()=>clearInterval(timer)},[session]);

  useEffect(()=>{let raf=0,last=performance.now(),lastPaint=0;activeClearingLoops++;if(import.meta.env.DEV&&activeClearingLoops>1)console.warn("More than one Clearing simulation loop is active",{activeClearingLoops});
    const tick=(now:number)=>{const rawDelta=(now-last)/1000,dt=Math.min(Math.max(rawDelta,0),.05);if(import.meta.env.DEV&&rawDelta>.25)console.warn("Clearing frame delta clamped",{rawDelta});last=now;if(document.visibilityState!=="visible"||gameplayStateRef.current!=="running"){raf=requestAnimationFrame(tick);return;} const pet=petPosRef.current;
      let activeAttackers=enemiesRef.current.filter(enemy=>["pursuing","windup","recovering"].includes(enemy.state)).length;
      for(const e of enemiesRef.current){
        if(e.state==="defeated"||e.state==="respawning"){if(now>=e.nextActionAt){e.x=e.homeX;e.y=e.homeY;e.health=e.maxHealth;e.engagedByPlayer=false;e.state="spawning";e.nextActionAt=now+500;}continue;}
        if(e.state==="spawning"){if(now>=e.nextActionAt){e.state="roaming";e.nextActionAt=now+randomBetween(CFG.roamPauseMs.min,CFG.roamPauseMs.max);}continue;}
        const d=pixelDistance(e,pet,worldPixels);
        if(e.engagedByPlayer&&e.state==="roaming"&&activeAttackers<CFG.maxSimultaneousAttackers){e.state="pursuing";activeAttackers++;}
        if((e.state==="pursuing"||e.state==="windup"||e.state==="recovering")&&d>CFG.disengageRadiusPixels){e.state="returning";e.targetX=CFG.homes[e.slot].x;e.targetY=CFG.homes[e.slot].y;}
        if(e.state==="roaming"&&now>=e.nextActionAt){const ang=Math.random()*Math.PI*2,r=Math.random()*CFG.roamRadiusPixels*.55;e.targetX=e.homeX+Math.cos(ang)*r/worldPixels.width;e.targetY=e.homeY+Math.sin(ang)*r/worldPixels.height;Object.assign(e,clampPoint(e,CFG.worldBounds));const target=clampPoint({x:e.targetX,y:e.targetY},CFG.worldBounds);e.targetX=target.x;e.targetY=target.y;e.nextActionAt=Infinity;}
        if(e.state==="pursuing"&&d<=CFG.attackRangePixels){e.state="windup";e.nextActionAt=now+CFG.attackWindupMs;}
        else if(e.state==="windup"&&now>=e.nextActionAt){if(d<=CFG.attackRangePixels&&now>=invulnerableUntil.current&&defeatedUntil.current<=now){const hp=Math.max(0,petHealthRef.current-e.attack);petHealthRef.current=hp;setPetHealth(hp);setRecentlyDamaged(true);if(recentDamageTimer.current)clearTimeout(recentDamageTimer.current);recentDamageTimer.current=setTimeout(()=>{setRecentlyDamaged(false);recentDamageTimer.current=null;},CFG.recentDamageDisplayMs);invulnerableUntil.current=now+CFG.petInvulnerabilityMs;if(hp===0){defeatedUntil.current=Number.POSITIVE_INFINITY;invulnerableUntil.current=Number.POSITIVE_INFINITY;}}e.state="recovering";e.nextActionAt=now+CFG.attackCooldownMs;}
        else if(e.state==="recovering"&&now>=e.nextActionAt)e.state="pursuing";
        let tx=e.targetX,ty=e.targetY;let speed:number=CFG.roamSpeedPixels;
        if(e.state==="pursuing"){tx=pet.x;ty=pet.y;speed=CFG.pursuitSpeedPixels;} else if(e.state==="returning"){tx=e.homeX;ty=e.homeY;speed=CFG.roamSpeedPixels;}
        if(e.state==="roaming"||e.state==="pursuing"||e.state==="returning"){const delta=pixelDelta(e,{x:tx,y:ty},worldPixels),len=Math.hypot(delta.dx,delta.dy);if(len>2){Object.assign(e,clampPoint(stepToward(e,{x:tx,y:ty},speed*dt,worldPixels),CFG.worldBounds));e.facingLeft=nextEnemyFacing(e.facingLeft?"left":"right",delta.dx,CFG.facingDeadZonePixels)==="left";}else if(e.state==="returning"){resetEnemyPassive(e);e.nextActionAt=now+1000;}else if(e.state==="roaming"&&e.nextActionAt===Infinity)e.nextActionAt=now+randomBetween(CFG.roamPauseMs.min,CFG.roamPauseMs.max);}
      }
      const separable=enemiesRef.current.filter(e=>!["defeated","respawning","spawning"].includes(e.state));resolveEnemyPairs(separable,worldPixels);for(const e of separable)Object.assign(e,clampPoint(e,CFG.worldBounds));
      if(import.meta.env.DEV&&enemiesRef.current.some(entity=>!Number.isFinite(entity.x)||!Number.isFinite(entity.y)))console.warn("Clearing rejected a non-finite entity coordinate");
      if(now-lastPaint>50){setEnemies(enemiesRef.current.map(e=>({...e})));lastPaint=now;}raf=requestAnimationFrame(tick);
    };raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);activeClearingLoops=Math.max(0,activeClearingLoops-1);};
  },[worldPixels.width,worldPixels.height]);

  const attack=useCallback((e:React.PointerEvent)=>{e.preventDefault();e.stopPropagation();const now=performance.now();if(gameplayStateRef.current!=="running"||!session){setFeedback([sessionState==="loading"?"Combat loading…":"Combat paused"]);return;}if(now<defeatedUntil.current)return;if(attackPhaseRef.current!=="idle"||now-lastAttack.current<CFG.petAttackCooldownMs){setFeedback(["Cooling down"]);return;}const p=petPosRef.current,weapon=equipment.loadout.data?.weapon??session.loadout.weapon,style=resolveClearingAttackStyle(weapon?{attackStyle:weapon.attackStyle,name:weapon.name}:undefined),range=style==="staff_orb"?CFG.staffAttackRangePixels:CFG.petAttackRangePixels;
    const petCenter={x:p.x,y:p.y-petSize*.45/worldPixels.height};
    const target=nearestValidClearingTarget(petCenter,enemiesRef.current.map(enemy=>({enemy,health:enemy.health,active:!['defeated','respawning','spawning'].includes(enemy.state),center:{x:enemy.x,y:enemy.y-enemyVisibleHeight(enemy.isBoss)*.45/worldPixels.height},collisionRadius:enemy.visibleHalfWidth})),range,worldPixels);
    if(!target){lastAttack.current=now;setFeedback(["Miss"]);return;}
    const targetCenter={x:target.x,y:target.y-enemyVisibleHeight(target.isBoss)*.45/worldPixels.height},direction=directionToClearingTarget(petCenter,targetCenter,worldPixels),slashFacesLeft=direction.dx<0;
    lastAttack.current=now;setAttackFacingLeft(slashFacesLeft);setAttackDirection({angleRadians:direction.angleRadians,distance:Math.hypot(direction.dx,direction.dy)});setAttackPhase("windup");
    const lockedInstanceId=target.instanceId;
    const impactTimer=setTimeout(async()=>{setAttackPhase("impact");
      if(target.instanceId!==lockedInstanceId||target.health<=0||['defeated','respawning','spawning'].includes(target.state)){setFeedback(["Target lost"]);return;}
      try{if(style==="staff_orb")await new Promise(resolve=>setTimeout(resolve,240));const r=await fetch("/api/explore/elysian-clearing/attack",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.sessionId,enemyInstanceId:target.instanceId,targetPosition:{x:target.x,y:target.y}})});if(!r.ok)throw new Error(`Attack rejected (${r.status})`);const data=await r.json();target.health=data.health;if(data.defeated){const defeated={effectId:`${target.instanceId}-${++effectSequence.current}`,enemyInstanceId:target.instanceId,x:target.x,y:target.y,exp:Number(data.expAwarded||0)};setDeathEffects(current=>[...current,defeated]);const effectTimer=setTimeout(()=>{setDeathEffects(current=>current.filter(effect=>effect.effectId!==defeated.effectId));timers.current.delete(effectTimer);},CFG.deathEffect.durationMs);timers.current.add(effectTimer);target.engagedByPlayer=false;target.state="defeated";target.nextActionAt=data.eggDrop?Infinity:performance.now()+randomBetween(CFG.respawnDelayMs.min,CFG.respawnDelayMs.max);if(data.chest)setChests(current=>current.some(chest=>chest.chestId===data.chest.chestId)?current:[...current,data.chest]);if(data.eggDrop)setEggDrops(current=>current.some(drop=>drop.id===data.eggDrop.id)?current:[...current,data.eggDrop]);if(data.nextEnemy){target.instanceId=data.nextEnemy.instanceId;target.health=data.nextEnemy.health;}setFeedback([data.boss?`Boss defeated · +${data.expAwarded} EXP`:`Enemy defeated · +${data.expAwarded} EXP`,data.eggDrop?"A special egg appeared":"Treasure chest appeared"]);setTimeout(()=>setFeedback([]),1800);}else{engageConfirmedEnemy(enemiesRef.current,target.instanceId);setFeedback([`-${data.damage??""} Hit`]);}setEnemies(enemiesRef.current.map(x=>({...x})));}catch(error){setFeedback(["Attack failed"]);console.error("Elysian Clearing attack failed",error instanceof Error?error.message:"Unknown error");}
    },CLEARING_SWORD_TIMING.windupMs);timers.current.add(impactTimer);
    const recoveryTimer=setTimeout(()=>setAttackPhase("recovery"),CLEARING_SWORD_TIMING.windupMs+CLEARING_SWORD_TIMING.impactMs);timers.current.add(recoveryTimer);
    const idleTimer=setTimeout(()=>setAttackPhase("idle"),CLEARING_SWORD_TIMING.totalMs);timers.current.add(idleTimer);
  },[session,sessionState,worldPixels,petSize,equipment.loadout.data?.weapon]);

  const collectChest=async(chest:ClearingRewardChest)=>{if(claimingChest)return;setClaimingChest(true);setChestError(null);try{const response=await fetch(`/api/explore/elysian-clearing/chests/${chest.chestId}/claim`,{method:"POST",credentials:"include"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"Unable to collect rewards");setFeedback([body.alreadyClaimed?"Rewards already collected":"Rewards collected"]);setTimeout(()=>setFeedback([]),1600);const dismissTimer=setTimeout(()=>{setChests(current=>current.filter(item=>item.chestId!==chest.chestId));setSelectedChest(current=>current?.chestId===chest.chestId?null:current);timers.current.delete(dismissTimer);},3200);timers.current.add(dismissTimer);await Promise.all([queryClient.invalidateQueries({queryKey:["/api/inventory"]}),queryClient.invalidateQueries({queryKey:["/api/clearing/inventory"]}),queryClient.invalidateQueries({queryKey:["/api/clearing/loadout"]}),queryClient.invalidateQueries({queryKey:["/api/auth/me"]})]);void balances.query.refetch();}catch(error){setChestError(error instanceof Error?error.message:"Unable to collect rewards");}finally{setClaimingChest(false);}};

  const collectEgg=async(drop:SpecialEggDrop)=>{if(!session)return;const response=await fetch(`/api/explore/elysian-clearing/eggs/${drop.id}/collect`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.sessionId})});const body=await response.json().catch(()=>({}));if(!response.ok){setFeedback([body.message||"Unable to collect egg"]);return;}setEggDrops(current=>current.filter(item=>item.id!==drop.id));setFeedback([`${drop.name} egg collected`]);await queryClient.invalidateQueries({queryKey:["/api/inventory"]});};

  const openChest=(chest:ClearingRewardChest)=>{if(openingChestId||selectedChest)return;setChestError(null);setOpeningChestId(chest.chestId);const timer=setTimeout(()=>{setOpeningChestId(null);setSelectedChest(chest);void collectChest(chest);timers.current.delete(timer);},180);timers.current.add(timer);};

  const threatened = enemies.some(enemy => enemy.health > 0 && ["pursuing", "windup", "recovering"].includes(enemy.state));
  const healthPercent = Math.max(0, Math.min(100, 100 * petHealth / Math.max(1, petMaxHealth)));
  const weaponOrigin = clearingWeaponOrigin(petPos,petSize,worldPixels,attackFacingLeft);
  if(import.meta.env.DEV&&(!Number.isFinite(weaponOrigin.x)||!Number.isFinite(weaponOrigin.y)))console.warn("Clearing weapon origin is invalid",weaponOrigin);
  const healthColor = healthPercent <= 25 ? "#ef4444" : healthPercent <= 50 ? "#eab308" : "#22c55e";
  const mutateLoadout=async(action:()=>Promise<unknown>)=>{try{await action();setFeedback(["Clearing loadout updated"]);setTimeout(()=>setFeedback([]),1800)}catch{setFeedback(["Equipment update failed"]);}};
  const usePotion=async(slotIndex:number)=>{const inventoryId=potionSlots[slotIndex],potion=availablePotions.find(item=>item.inventoryId===inventoryId);if(!potion||usingPotionRef.current||gameplayStateRef.current!=="running")return;usingPotionRef.current=true;setUsingPotion(true);try{const response=await fetch("/api/explore/use-potion",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryId:potion.inventoryId,petInventoryId:session?.pet.inventoryId})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"Potion could not be used");if(Number(body.healAmount)>0){const healed=Math.min(petMaxHealthRef.current,petHealthRef.current+Number(body.healAmount));petHealthRef.current=healed;setPetHealth(healed);}setFeedback([Number(body.healAmount)>0?`Restored ${body.healAmount} health`:`Restored ${body.manaAmount} mana`]);setTimeout(()=>setFeedback([]),1600);if(body.depleted)setPotionSlots(current=>current.map((id,index)=>index===slotIndex?null:id));await queryClient.invalidateQueries({queryKey:["/api/inventory"]});}catch(error){setFeedback([error instanceof Error?error.message:"Potion could not be used"]);setTimeout(()=>setFeedback([]),1800);}finally{usingPotionRef.current=false;setUsingPotion(false);}};
  const fixedHud = <>
    <div className="absolute pointer-events-auto flex items-center gap-2" style={{left:14,top:"max(61px, calc(env(safe-area-inset-top, 0px) + 61px))",zIndex:18}}><button data-interactive data-testid="button-clearing-equipment" aria-label="Open pet equipment" onClick={()=>setEquipmentOpen(true)} className="clearing-action-button h-[42px] w-[42px] overflow-hidden rounded-full bg-emerald-950"><img src={activePet?.hatchedImageUrl||activePet?.imageUrl||fallbackPet} onError={e=>{e.currentTarget.src=fallbackPet}} alt="Active pet" className="h-full w-full object-contain"/></button></div>
    <div data-testid="clearing-currency-display" aria-live="polite" className="absolute right-3 pointer-events-none flex gap-2 rounded-xl border border-amber-500/70 bg-emerald-950/90 px-2 py-1 text-xs font-bold text-amber-100 shadow-lg" style={{top:"max(58px, calc(env(safe-area-inset-top, 0px) + 58px))",zIndex:17}}><span className="flex items-center gap-1"><img src={currencyAssets.essenceToken} alt="Essence" className="h-5 w-5 object-contain"/>{balances.loading?"…":balances.error?"—":balances.formattedEssence}</span><span className="flex items-center gap-1"><img src={currencyAssets.coin} alt="Coins" className="h-5 w-5 object-contain"/>{balances.loading?"…":balances.error?"—":balances.formattedCoin}</span></div>
    <ClearingEquipmentModal open={equipmentOpen} onOpenChange={setEquipmentOpen} onOpenInventory={()=>setInventoryOpen(true)} inventory={equipment.inventory.data} loadout={equipment.loadout.data} onUnequip={slot=>void mutateLoadout(()=>equipment.unequip.mutateAsync(slot))} onEquip={id=>void mutateLoadout(()=>equipment.equip.mutateAsync(id))}/>
    <ClearingInventoryPanel open={inventoryOpen} onOpenChange={setInventoryOpen} items={equipment.inventory.data} loadout={equipment.loadout.data} onEquip={id=>void mutateLoadout(()=>equipment.equip.mutateAsync(id))} onSell={ids=>equipment.sell.mutateAsync(ids)}/>

    {feedback.length>0&&<div className="absolute left-1/2 top-1/4 -translate-x-1/2 text-center font-bold text-yellow-200 pointer-events-none" style={{zIndex:20,textShadow:"0 2px 4px #000"}}>{feedback.map(x=><div key={x}>{x}</div>)}</div>}
    {sessionState==="error"&&<button data-interactive data-testid="button-clearing-retry" type="button" className="clearing-action-button absolute left-1/2 top-[32%] -translate-x-1/2 rounded-lg bg-emerald-950 px-4 py-2 font-bold text-amber-100" style={{zIndex:21}} onClick={()=>{setFeedback([]);setSessionAttempt(v=>v+1)}}>Retry</button>}
    <div data-testid="clearing-potion-slots" className="absolute pointer-events-auto flex gap-2" style={{right:"max(91px, calc(env(safe-area-inset-right) + 91px))",bottom:"max(25px, env(safe-area-inset-bottom))",zIndex:16}}>{[0,1,2].map(index=>{const potion=availablePotions.find(item=>item.inventoryId===potionSlots[index]);return <button key={index} type="button" data-interactive data-testid={`button-clearing-potion-${index}`} aria-label={potion?`Use ${potion.name}`:`Equip potion in slot ${index+1}`} disabled={usingPotion||petHealth<=0} onClick={()=>potion?void usePotion(index):setPotionPickerSlot(index)} className="clearing-action-button relative flex h-12 w-12 items-center justify-center rounded-full bg-emerald-950/85 disabled:opacity-50">{potion?<><img src={potion.imageUrl||fallbackPet} alt="" className="h-8 w-8 object-contain"/><span className="absolute -bottom-1 -right-1 min-w-5 rounded-full bg-black px-1 text-[10px] font-black text-white">{potion.quantity}</span></>:<span className="text-lg font-black text-emerald-100/60">+</span>}</button>})}</div>
    <button disabled={sessionState!=="ready"||petHealth<=0} data-interactive data-testid="button-clearing-attack" aria-label="Sword attack" onPointerDown={attack} className="clearing-action-button absolute pointer-events-auto rounded-full disabled:opacity-50 text-white flex items-center justify-center" style={{right:"max(20px, env(safe-area-inset-right))",bottom:"max(20px, env(safe-area-inset-bottom))",width:CFG.attackButtonSize,height:CFG.attackButtonSize,zIndex:15,touchAction:"none",background:"#294b35",boxShadow:"0 3px 12px #000"}}><Sword aria-hidden size={28}/></button>
    {potionPickerSlot!==null&&<div data-interactive role="dialog" aria-modal="true" aria-label="Choose a Clearing potion" className="absolute inset-0 pointer-events-auto flex items-end justify-center bg-black/55 p-4" style={{zIndex:30}} onPointerDown={event=>event.stopPropagation()}><div className="mb-20 w-full max-w-sm rounded-2xl border border-emerald-300/60 bg-emerald-950 p-4 text-emerald-50 shadow-2xl"><div className="mb-3 flex items-center justify-between"><h2 className="font-black text-amber-200">Equip a potion</h2><button type="button" className="h-10 rounded-lg px-3" onClick={()=>setPotionPickerSlot(null)}>Close</button></div><p className="mb-3 text-xs text-emerald-100/75">Health and mana potions only. Each slot holds a stack of up to 50.</p><div className="grid max-h-56 grid-cols-3 gap-3 overflow-y-auto">{availablePotions.filter(potion=>!potionSlots.includes(potion.inventoryId)).map(potion=><button key={potion.inventoryId} type="button" className="relative flex min-h-24 flex-col items-center justify-center rounded-xl border border-emerald-400/40 bg-black/20 p-2 text-xs" onClick={()=>{setPotionSlots(current=>current.map((id,index)=>index===potionPickerSlot?potion.inventoryId:id));setPotionPickerSlot(null);}}><img src={potion.imageUrl||fallbackPet} alt="" className="h-11 w-11 object-contain"/><b className="line-clamp-2">{potion.name}</b><span>×{potion.quantity}</span></button>)}{availablePotions.filter(potion=>!potionSlots.includes(potion.inventoryId)).length===0&&<p className="col-span-3 py-6 text-center text-sm text-emerald-100/70">No eligible potions in your bag.</p>}</div></div></div>}
    {petHealth<=0&&<div data-interactive role="dialog" aria-modal="true" aria-labelledby="clearing-defeat-title" className="absolute inset-0 pointer-events-auto flex items-center justify-center bg-black/70 p-5" style={{zIndex:40}} onPointerDown={event=>event.stopPropagation()}><div className="w-full max-w-sm rounded-2xl border-2 border-red-300/70 bg-emerald-950 p-6 text-center text-amber-50 shadow-2xl"><h2 id="clearing-defeat-title" className="text-2xl font-black text-red-200">You were defeated</h2><p className="mt-3 text-emerald-100">Your pet ran out of health in the Elysian Bayou Clearing. Return to the main world to recover before trying again.</p><button type="button" data-testid="button-clearing-defeat-return" className="mt-6 min-h-12 w-full rounded-xl bg-amber-400 px-4 py-3 font-black text-emerald-950" onClick={onReturnToWorld}>Return to Main World</button></div></div>}
  </>;

  return <>
    {eggDrops.map(drop=>{const colors=["#86efac","#60a5fa","#c084fc","#f472b6","#fde047"],color=colors[Math.max(0,Math.min(4,drop.stars-1))];return <button key={drop.id} type="button" data-interactive data-testid="clearing-special-egg-drop" aria-label={`Collect ${drop.name} egg, ${drop.stars} stars`} onClick={()=>void collectEgg(drop)} className="absolute pointer-events-auto flex h-16 w-16 flex-col items-center justify-center rounded-full" style={{left:`${drop.worldX*100}%`,top:`${drop.worldY*100}%`,transform:"translate(-50%,-70%)",zIndex:worldYToDepth(drop.worldY,1),filter:`drop-shadow(0 0 10px ${color})`}}><span className="absolute inset-1 rounded-full opacity-40 animate-pulse" style={{background:color}}/><img src={drop.eggImageUrl||fallbackPet} alt="" className="relative h-11 w-11 object-contain"/><span className="relative -mt-1 whitespace-nowrap text-[10px] font-black" style={{color,textShadow:"0 1px 2px #000"}}>{"★".repeat(drop.stars)}</span></button>})}
    <ClearingChestLayer chests={chests} openingChestId={openingChestId} openedChestId={selectedChest?.chestId??null} claimError={chestError} onOpen={openChest} onRetry={chest=>void collectChest(chest)}/>
    {(threatened||recentlyDamaged)&&<div data-testid="clearing-pet-health-bar" className="absolute pointer-events-none" style={{left:`${petPos.x*100}%`,top:`${petPos.y*100}%`,width:CFG.petHealthBar.width,height:CFG.petHealthBar.height,transform:`translate(-50%, -${petSize*CLEARING_PET_PRESENTATION.feetAnchor+CFG.petHealthBar.gap}px)`,zIndex:worldYToDepth(petPos.y,2),border:"1px solid rgba(255,255,255,.45)",borderRadius:999,background:"rgba(0,0,0,.7)",overflow:"hidden"}}><div className="h-full transition-[width]" style={{width:`${healthPercent}%`,background:healthColor}} /></div>}
    {enemies.map(e=>{if(["spawning","defeated","respawning"].includes(e.state))return null;const url=e.imageUrl||CFG.enemyImageUrl,m=imageMetrics[url]||FALLBACK_ENEMY_IMAGE_METRICS,visibleHeight=enemyVisibleHeight(e.isBoss),canvasHeight=visibleHeight/m.heightRatio,canvasWidth=canvasHeight*m.canvasWidth/m.canvasHeight;return <div key={e.instanceId} data-enemy-rank={e.isBoss?"boss":"regular"} className="absolute pointer-events-none" style={{left:`${e.x*100}%`,top:`${e.y*100}%`,width:canvasWidth,height:canvasHeight,transform:`translate(${-50-m.feetOffsetX/m.canvasWidth*100}%,${-50-m.feetOffsetY/m.canvasHeight*100}%) scaleX(${enemyFlipScale(e.facingLeft?"left":"right",CFG.naturalFacing)})`,zIndex:worldYToDepth(e.y),filter:e.state==="windup"?"drop-shadow(0 0 9px #ff3b30) brightness(1.25)":e.isBoss?"drop-shadow(0 0 6px rgba(251,191,36,.9))":"none"}}>{e.isBoss&&<><span aria-hidden className="absolute left-1/2 top-1/2 -z-10 h-[76px] w-[76px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-amber-300/70 bg-amber-400/15 animate-pulse"/><span className="absolute -top-5 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full border border-amber-300/70 bg-amber-950/85 px-2 py-px text-[9px] font-black uppercase tracking-widest text-amber-100">Boss · {e.name||CFG.enemyName}</span></>}<span className="absolute rounded-[50%] bg-black/30 blur-[2px]" style={{width:m.visibleWidth/m.visibleHeight*visibleHeight*.72,height:8,left:`${(m.leftRatio+m.widthRatio/2)*100}%`,top:`${(m.topRatio+m.heightRatio)*100}%`,transform:"translate(-50%,-50%)"}}/><img src={url} onError={event=>{event.currentTarget.src=fallbackPet}} alt={e.name||CFG.enemyName} className="w-full h-full object-contain" draggable={false}/>{(e.health<e.maxHealth||e.state!=="roaming"||e.isBoss)&&<div className="absolute -top-1 left-2 right-2 h-1.5 rounded bg-black/70 overflow-hidden"><div className={`h-full ${e.isBoss?"bg-amber-400":"bg-red-500"}`} style={{width:`${100*e.health/e.maxHealth}%`}}/></div>}</div>})}
    {deathEffects.map(effect=><div key={effect.effectId} data-enemy-instance-id={effect.enemyInstanceId} data-testid="clearing-enemy-death-effect" className="absolute pointer-events-none" style={{left:`${effect.x*100}%`,top:`${effect.y*100}%`,width:CFG.deathEffect.size,height:CFG.deathEffect.size,transform:"translate(-50%,-75%)",zIndex:worldYToDepth(effect.y,CLEARING_WORLD_LAYERS.effectOffset)}}><img src={skullUrl} alt="" className="h-full w-full object-contain animate-clearing-skull" draggable={false}/>{effect.exp>0&&<span className="absolute left-1/2 top-0 -translate-x-1/2 whitespace-nowrap text-xs font-black text-sky-100 drop-shadow">+{effect.exp} EXP</span>}</div>)}
    <ClearingAttackEffect weapon={equipment.loadout.data?.weapon??session?.loadout.weapon??null} phase={attackPhase} facingLeft={attackFacingLeft} angleRadians={attackDirection.angleRadians} targetDistance={attackDirection.distance} x={weaponOrigin.x} y={weaponOrigin.y} petSize={petSize} playerY={petPos.y}/>
    <style>{`.clearing-chest-shadow{position:absolute;left:8px;right:8px;bottom:5px;height:9px;border-radius:50%;background:rgba(0,0,0,.38);filter:blur(3px)}@keyframes clearing-chest-open{0%{transform:scale(1)}45%{transform:scale(.9) translateY(2px)}100%{transform:scale(1)}}.animate-clearing-chest-open{animation:clearing-chest-open 180ms ease-out}@keyframes clearing-drop-rise{0%{opacity:0;transform:translate(-50%,-50%) scale(.35)}70%{opacity:1;transform:translate(calc(-50% + var(--drop-x)),calc(-50% + var(--drop-y))) scale(1.1)}100%{opacity:1;transform:translate(calc(-50% + var(--drop-x)),calc(-50% + var(--drop-y))) scale(1)}}.clearing-chest-drop{opacity:0;animation:clearing-drop-rise 440ms cubic-bezier(.2,.8,.2,1) var(--drop-delay) forwards}@keyframes clearing-skull-defeat{0%{opacity:0;transform:translateY(4px) scale(.7)}18%{opacity:1;transform:translateY(0) scale(1)}100%{opacity:0;transform:translateY(-${CFG.deathEffect.risePixels}px) scale(1)}}.animate-clearing-skull{animation:clearing-skull-defeat ${CFG.deathEffect.durationMs}ms ease-out forwards}.clearing-chest-sparkles{position:absolute;inset:-4px;pointer-events:none;color:#c4b5fd}.clearing-chest-sparkles-epic{color:#e879f9}.clearing-chest-sparkles-legendary{color:#fde047}.clearing-chest-sparkles i{position:absolute;width:5px;height:5px;background:currentColor;clip-path:polygon(50% 0,62% 38%,100% 50%,62% 62%,50% 100%,38% 62%,0 50%,38% 38%);animation:clearing-sparkle 1.8s ease-in-out infinite}.clearing-chest-sparkles i:nth-child(1){left:4px;top:9px}.clearing-chest-sparkles i:nth-child(2){right:3px;top:18px;animation-delay:.6s}.clearing-chest-sparkles i:nth-child(3){left:25px;top:0;animation-delay:1.1s}@keyframes clearing-sparkle{0%,65%,100%{opacity:0;transform:scale(.4)}75%{opacity:1;transform:scale(1)}}@media(prefers-reduced-motion:reduce){.animate-clearing-skull,.animate-clearing-chest-open,.clearing-chest-drop{animation:none}.clearing-chest-drop{opacity:1;transform:translate(calc(-50% + var(--drop-x)),calc(-50% + var(--drop-y)))}}`}</style>
    {hudElement&&createPortal(fixedHud,hudElement)}
  </>;
}
