import{useState}from"react";import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import{apiRequest}from"@/lib/queryClient";import{readFileAsDataUrl}from"@/lib/utils";import{Pencil,Plus,Trash2,Upload}from"lucide-react";
type Enemy={id:string;name:string;imageUrl:string|null};
export default function EnemyDatabasePanel(){const q=useQuery<Enemy[]>({queryKey:["/api/admin/enemies"]}),qc=useQueryClient();const[name,setName]=useState(""),[imageData,setImageData]=useState<string|null>(null),[preview,setPreview]=useState<string|null>(null),[editing,setEditing]=useState<Enemy|null>(null),[open,setOpen]=useState(false);
 const save=useMutation({mutationFn:async()=>{const body={name:name.trim(),imageData:imageData??undefined};return(await apiRequest(editing?"PATCH":"POST",editing?`/api/admin/enemies/${editing.id}`:"/api/admin/enemies",body)).json()},onSuccess:()=>{qc.invalidateQueries({queryKey:["/api/admin/enemies"]});setOpen(false);setEditing(null);setName("");setImageData(null);setPreview(null)}});
 const remove=useMutation({mutationFn:(id:string)=>apiRequest("DELETE",`/api/admin/enemies/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:["/api/admin/enemies"]})});
 const pick=()=>{const i=document.createElement("input");i.type="file";i.accept="image/*";i.onchange=async()=>{const f=i.files?.[0];if(f){const d=await readFileAsDataUrl(f);setImageData(d);setPreview(d)}};i.click()};
 const edit=(e:Enemy)=>{setEditing(e);setName(e.name);setPreview(e.imageUrl);setImageData(null);setOpen(true)};
 return <section data-testid="enemy-database-panel" className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-fantasy text-lg text-red-300">Enemy artwork</h3><p className="text-xs text-stone-400">Reusable identity only. Clearing stats and boss status are configured in Clearing.</p></div><button onClick={()=>{setEditing(null);setName("");setPreview(null);setOpen(true)}} className="rounded-lg bg-red-900 px-3 py-2 text-red-100"><Plus className="inline h-4 w-4"/> Add</button></div>
 {open&&<div className="rounded-xl border border-red-800 bg-black/30 p-4 space-y-3"><input data-testid="input-enemy-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Enemy name" className="w-full rounded bg-black/40 p-2 text-white"/><button data-testid="button-pick-enemy-image" onClick={pick} className="flex min-h-24 w-full items-center justify-center rounded border border-dashed border-red-700">{preview?<img src={preview} alt="Enemy preview" className="h-24 object-contain"/>:<><Upload className="mr-2"/> Upload enemy image</>}</button><div className="flex gap-2"><button data-testid="button-submit-enemy" disabled={!name.trim()||save.isPending} onClick={()=>save.mutate()} className="rounded bg-red-800 px-4 py-2 text-white">{save.isPending?"Saving…":editing?"Save Changes":"Add Enemy"}</button><button onClick={()=>setOpen(false)} className="rounded border px-4 py-2">Cancel</button></div></div>}
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{(q.data??[]).map(e=><article key={e.id} className="rounded-xl border border-red-900/50 bg-black/30 p-3"><div className="h-28">{e.imageUrl?<img src={e.imageUrl} alt={e.name} className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center text-stone-500">No image</div>}</div><b className="block truncate text-red-100">{e.name}</b><div className="mt-2 flex gap-2"><button aria-label={`Edit ${e.name}`} onClick={()=>edit(e)}><Pencil className="h-4 w-4"/></button><button aria-label={`Delete ${e.name}`} onClick={()=>remove.mutate(e.id)}><Trash2 className="h-4 w-4 text-red-400"/></button></div></article>)}</div></section>}
