import { useEffect, useState } from "react";
import { currencyAssets } from "@/lib/currencyAssets";

type Pet={inventoryId:string;name:string;nickname?:string|null;imageUrl?:string|null;rarity:number;essenceValue:number;eligible:boolean;unavailableReason?:string|null};
export default function SoulExchangeOverlay({backgroundUrl,onClose}:{backgroundUrl:string|null;onClose:()=>void}){
 const [pets,setPets]=useState<Pet[]>([]),[essence,setEssence]=useState(0),[selected,setSelected]=useState<Pet|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[gain,setGain]=useState<number|null>(null);
 const load=async()=>{const r=await fetch("/api/soul-exchange/pets",{credentials:"include"});if(!r.ok)throw new Error("Could not hear the waiting souls.");const d=await r.json();setPets(d.pets);setEssence(d.essence)};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const exchange=async()=>{if(!selected||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/soul-exchange/exchange",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({petInventoryId:selected.inventoryId,exchangeActionId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw new Error(d.message||"The ritual could not be completed.");setConfirm(false);setGain(d.essenceAwarded);setEssence(d.newEssenceBalance);setTimeout(()=>{setPets(v=>v.filter(p=>p.inventoryId!==selected.inventoryId));setSelected(null)},550);setTimeout(()=>setGain(null),1800)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-50 overflow-hidden bg-[#090314]" style={{maxWidth:768,margin:"0 auto"}}>
  {backgroundUrl&&<><img aria-hidden src={backgroundUrl} className="absolute inset-0 h-full w-full object-cover opacity-35 blur-lg"/><img src={backgroundUrl} alt="" className="absolute inset-0 h-full w-full object-contain"/></>}
  <div className="absolute inset-0 bg-gradient-to-b from-black/65 via-transparent to-[#090314]/90"/>
  <main className="relative z-10 flex h-full flex-col overflow-hidden px-3" style={{paddingTop:"max(12px, env(safe-area-inset-top))",paddingBottom:"max(12px, env(safe-area-inset-bottom))"}}>
   <header className="flex items-center gap-2 rounded-2xl border border-violet-300/30 bg-black/45 p-3 backdrop-blur-sm"><div className="min-w-0 flex-1"><h1 className="font-fantasy text-xl font-black tracking-wider text-violet-100">The Soul Exchange</h1><p className="text-xs text-violet-200/70">Release a companion into the violet beyond.</p></div><span className="flex items-center gap-1 font-black text-amber-200"><img src={currencyAssets.essenceToken} alt="Essence" className="h-7 w-7"/>{essence.toLocaleString()}</span><button onClick={onClose} aria-label="Close Soul Exchange" className="min-h-11 min-w-11 rounded-full border border-violet-200/40 bg-black/50 text-xl text-white">×</button></header>
   <section className={`relative mx-auto flex h-40 w-40 flex-none items-center justify-center transition ${selected?"scale-105 brightness-125":""}`}><img src="/world-assets/worlds/haunted_woods/soul-exchange-portal.svg" alt="Soul Exchange portal" className="h-full w-full object-contain"/>{gain!==null&&<b aria-live="polite" className="absolute rounded-full bg-violet-200 px-3 py-1 text-violet-950 shadow-xl">+{gain} Essence</b>}</section>
   <section className="min-h-0 flex-1 overflow-y-auto rounded-2xl border border-violet-300/25 bg-[#140b26]/75 p-3 backdrop-blur-sm"><h2 className="mb-2 font-bold text-violet-100">Choose a hatched pet</h2>{error&&<p role="alert" className="mb-2 rounded-lg bg-red-950/80 p-2 text-sm text-red-100">{error}</p>}
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{pets.map(p=><button key={p.inventoryId} disabled={!p.eligible||busy} onClick={()=>setSelected(p)} className={`min-h-44 rounded-xl border p-2 text-center transition active:scale-[.98] ${selected?.inventoryId===p.inventoryId?"border-amber-300 bg-violet-700/65 shadow-[0_0_18px_#8b5cf6]":"border-violet-300/25 bg-black/35"} disabled:opacity-60`}><img src={p.imageUrl||""} alt="" className="mx-auto h-20 w-20 object-contain"/><b className="block truncate text-violet-50">{p.nickname||p.name}</b><span className="block text-amber-300" aria-label={`${p.rarity} star rarity`}>{"★".repeat(p.rarity)}</span><span className="block text-sm font-bold text-violet-100">{p.essenceValue.toLocaleString()} Essence</span>{!p.eligible&&<small className="mt-1 block leading-tight text-rose-200">{p.unavailableReason}</small>}</button>)}</div>
    {!pets.length&&<div className="py-10 text-center text-violet-100"><b>No souls are ready for exchange.</b><p className="mt-2 text-sm text-violet-200/70">Hatched pets that are not equipped, active, listed, or in use will appear here.</p></div>}
   </section>
   <button disabled={!selected||busy} onClick={()=>setConfirm(true)} className="mt-3 min-h-12 w-full rounded-xl bg-gradient-to-r from-violet-600 to-amber-500 font-black text-white shadow-lg disabled:opacity-45">{selected?`Exchange for ${selected.essenceValue.toLocaleString()} Essence`:"Select a pet"}</button>
  </main>
  {confirm&&selected&&<div role="alertdialog" aria-modal="true" aria-labelledby="soul-confirm-title" className="absolute inset-0 z-20 flex items-center justify-center bg-black/75 p-5"><div className="w-full max-w-sm rounded-2xl border-2 border-violet-300 bg-[#160929] p-5 text-center text-white"><h2 id="soul-confirm-title" className="text-xl font-black text-violet-100">Release {selected.nickname||selected.name} to the Soul Exchange?</h2><p className="my-4 text-rose-100">Your pet will permanently leave your inventory.</p><p>You will receive:<b className="mt-1 block text-2xl text-amber-300">{selected.essenceValue.toLocaleString()} Essence</b></p><div className="mt-6 grid gap-3"><button disabled={busy} onClick={()=>setConfirm(false)} className="min-h-12 rounded-xl border border-violet-200/50">Cancel</button><button disabled={busy} onClick={()=>void exchange()} className="min-h-12 rounded-xl bg-violet-500 font-black disabled:opacity-50">{busy?"Exchanging…":"Exchange Pet"}</button></div></div></div>}
 </div>
}
